// Lists every model of src/effects/model-list.js with its file size, draw calls (mesh parts), material names and
// animation clips (with lengths in seconds). --write saves the table to docs/MODELS.md.
import { readFileSync, statSync, writeFileSync } from 'node:fs';
import { MODELS } from '../src/effects/model-list.js';

const rows = Object.entries(MODELS).map(([name, file]) => {
  const path = `assets/models/${file}`, b = readFileSync(path), j = JSON.parse(b.slice(20, 20 + b.readUInt32LE(12)).toString());
  const dc = (j.nodes ?? []).filter((n) => n.mesh !== undefined).reduce((s, n) => s + new Set(j.meshes[n.mesh].primitives.map((pr) => pr.material)).size, 0);   // models.js merges a mesh's parts by material
  const len = (a) => Math.max(...a.samplers.map((s) => j.accessors[s.input].max?.[0] ?? 0));
  const clips = (j.animations ?? []).map((a) => `${a.name} ${len(a).toFixed(1)}`).join(', ') || 'static';
  return { name, file, kb: Math.round(statSync(path).size / 1024), dc, mats: (j.materials ?? []).map((m) => m.name).join(', '), clips };
});
const out = ['# Models', '',
  'Generated by `node scripts/list-models.mjs --write` from `src/effects/model-list.js`. Use them in a scene with',
  '`createModel(name, { height })` and `pose(clip, t)` (`src/effects/models.js`); name them in the scene\'s catalog entry',
  '(`VM(dc, desc, [names])`). dc = draw calls the model adds (add the scene\'s own props). Clips: name and length in seconds.',
  'People share one rig (bones Head, Neck, Torso, Abdomen, Hips, Shoulder/UpperArm/LowerArm/Fist L R, UpperLeg/LowerLeg/Foot',
  'L R; three.js drops the dots: `FootL`), so a gesture made by turning bones after `pose()` works on all of them.', '',
  '| name | file | KB | dc | materials | clips |', '|---|---|---|---|---|---|',
  ...rows.map((r) => `| ${r.name} | ${r.file} | ${r.kb} | ${r.dc} | ${r.mats} | ${r.clips} |`), ''].join('\n');
if (process.argv.includes('--write')) { writeFileSync('docs/MODELS.md', out); console.log(`docs/MODELS.md: ${rows.length} models`); }
else console.log(out);
