// The native-review list: every reading and sentence a person still has to confirm -> docs/REVIEW.md.
// Usage: npm run review:list   (the content check fails when the file is out of date, like audio/clips.json)
// A sentence leaves the list when its card says "needsNativeReview": false.
import { readFileSync, writeFileSync } from 'node:fs';
import { pathToFileURL } from 'node:url';

const esc = (s) => String(s).replace(/\|/g, '\\|');
const ruby = (segs) => segs.map((g) => (g.reading ? `<ruby>${g.text}<rp>(</rp><rt>${g.reading}</rt><rp>)</rp></ruby>` : g.text)).join('');
const source = (s) => (s.source?.tatoeba ? `[Tatoeba ${s.source.tatoeba[0]}](https://tatoeba.org/en/sentences/show/${s.source.tatoeba[0]})` : 'written for the app');

function readings(card) {
  if (card.type === 'word') return `${card.primaryReading}${card.furigana.some((f) => f.reading) ? ` (${card.furigana.map((f) => f.reading ? `${f.text} ${f.reading}` : f.text).join(' · ')})` : ''}`;
  const { kun = [], on = [] } = card.readings ?? {};
  return `**${card.primaryReading}**${kun.length ? ` · kun ${kun.join('、')}` : ''}${on.length ? ` · on ${on.join('、')}` : ''}`;
}

export function buildReviewList() {
  const index = JSON.parse(readFileSync('content/decks/index.json', 'utf8'));
  const card = (id) => JSON.parse(readFileSync(`content/cards/${id}.json`, 'utf8'));
  let waiting = 0, done = 0;
  const sections = index.decks.filter((d) => d.enabled).map((d) => {
    const ids = JSON.parse(readFileSync(`content/decks/${d.file}`, 'utf8')).cards;
    const rows = ids.flatMap((id, i) => {
      const c = card(id);
      return c.sentences.map((s) => {
        if (!s.verified?.needsNativeReview) { done++; return null; }
        waiting++;
        return `| ${i + 1} | ${c.word ?? c.kanji} \`${c.id}\` | ${esc(readings(c))} | ${esc(c.meaning)} | ${ruby(s.segments)} | ${esc(s.en)} | ${source(s)} |`;
      }).filter(Boolean);
    });
    return `## ${d.title ?? d.id} (${ids.length} cards)\n\n| # | Card | Readings | Meaning | Sentence | English | Source |\n|---|---|---|---|---|---|---|\n${rows.join('\n')}\n`;
  });
  return `# Native review list

Generated by \`npm run review:list\` from the enabled decks. Do not edit by hand.

**For a native speaker or a teacher.** Every reading and sentence below was checked by two analysers (SudachiPy and Open
JTalk agree), but no person has confirmed them yet. Per row:
- Is the sentence natural Japanese?
- Is every reading right? Furigana sit over the kanji. For kanji cards, the reading in bold is the one taught first.
- Does the English mean the same thing?

Report problems by card id (the code in the Card column). To confirm a row yourself, set \`"needsNativeReview": false\`
on that sentence in \`content/cards/<id>.json\`, then run \`npm run review:list\`.

**Waiting:** ${waiting} sentence(s). **Confirmed:** ${done}.

${sections.join('\n')}`;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  writeFileSync('docs/REVIEW.md', buildReviewList());
  console.log('docs/REVIEW.md written');
}
