// Every voice clip the content needs -> audio/clips.json (the input of scripts/voicevox.mjs, which you run on your PC).
// Usage: npm run voice:list   (the content check fails when the file is out of date, so new cards are never forgotten)
// Per clip: id (what the app plays: src/content/clips.js), text to speak, the expected reading in katakana built from the
// card's verified segments, the expected *spoken* kana (particles は/へ/を as pronounced: ワ/エ/オ), and suggested speeds.
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { pathToFileURL } from 'node:url';
import { VOICE } from '../src/config.js';
import { readingClipId, sentenceClipId } from '../src/content/clips.js';

const kata = (s) => [...s].map((c) => (c >= 'ぁ' && c <= 'ゖ' ? String.fromCharCode(c.charCodeAt(0) + 0x60) : c)).join('');
const strip = (s) => s.replace(/[。、，．！？!?・「」『』（）\s]/g, '');
const PARTICLE = { 'は': 'ワ', 'へ': 'エ', 'を': 'オ' };          // a segment that is only this particle is pronounced like this

export function buildClipList(dir = 'content/cards') {
  const clips = [];
  for (const f of readdirSync(dir).filter((x) => x.endsWith('.json')).sort()) {
    const card = JSON.parse(readFileSync(`${dir}/${f}`, 'utf8'));
    const r = strip(kata(card.primaryReading));
    clips.push({ id: readingClipId(card), card: card.id, kind: 'reading', text: card.primaryReading, reading: r, spoken: r, speed: VOICE.readingSpeed });
    card.sentences.forEach((s, i) => {
      const text = s.segments.map((g) => g.text).join('');
      const reading = strip(kata(s.segments.map((g) => g.reading ?? g.text).join('')));
      const spoken = strip(kata(s.segments.map((g) => g.reading ?? PARTICLE[g.text] ?? g.text).join('')));
      clips.push({ id: sentenceClipId(card, i), card: card.id, kind: 'sentence', text, reading, spoken, en: s.en, speed: VOICE.speed });
    });
  }
  return { note: 'Generated by `npm run voice:list` from content/cards. Do not edit. Render with scripts/voicevox.mjs (docs/VOICEVOX.md).', clips };
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const list = buildClipList();
  writeFileSync('audio/clips.json', `{ "note": ${JSON.stringify(list.note)},\n  "clips": [\n${list.clips.map((c) => `    ${JSON.stringify(c)}`).join(',\n')}\n  ]\n}\n`);
  console.log(`audio/clips.json: ${list.clips.length} clips (${list.clips.filter((c) => c.kind === 'reading').length} readings, ${list.clips.filter((c) => c.kind === 'sentence').length} sentences)`);
}
