// Vignette catalog entries of the Step 3a model pass, batch 4 part c (spread into vignette-catalog.js).
import { VM, pdc } from './vcat-kit.js';

export const Q4C = {
  'q-piano-lesson': VM((o) => pdc(o.who, o.kid) + 6, '習う (models): a grandma at a keyboard plays three coloured notes while a little girl at a toy keyboard watches her hands; the girl plays the same three notes; grandma nods: じょうず!', (o) => [o.who, o.kid], { who: 'grandma', kid: 'gal3' }),
  'q-drum-fun': VM((o) => pdc(o.who) + 5, '楽 (models): a small boy beats a taiko drum with two sticks, right, left, right; the kanji squashes on every beat and notes fly up; he throws the sticks up and cheers: たのしい!', (o) => [o.who], { who: 'guy' }),
  'q-headphones-dance': VM((o) => pdc(o.who) + 2, '音楽 (models): a girl in big headphones dances, bouncing on the beat, pumping one arm up then the other, swaying; colourful notes pour out of the headphones', (o) => [o.who], { who: 'gal2' }),
  'q-bell-ring': VM((o) => pdc(o.who) + 5, '音 (models): a bell swings in a wooden frame and rings (カーン, rings of sound); a grandpa looking away turns toward it, cups his ear and nods: ♪', (o) => [o.who, 'bell'], { who: 'grandpa' }),
  'q-gift-bow': VM((o) => pdc(o.who) + 4, '御 (models): a woman in a kimono holds a wrapped gift out with both hands and bows deeply: どうぞ; the kanji bows back and sparkles (polite, honourable)', (o) => [o.who], { who: 'kimono' }),
  'q-devil-vase': VM((o) => pdc(o.who) + (o.outcome === 'thumbsdown' ? 13 : 9), '悪 (models): a little red devil sneaks up and knocks a vase off its stand; it smashes and he snickers; a woman turns (!), crosses her arms in a big X and shakes her head: だめ!, and he runs off; outcome thumbsdown: she points a big thumbs down at him and a rain cloud drizzles on him: わるい! (悪い)', (o) => [o.who], { who: 'gal3', outcome: 'devil' }, 'outcome'),
  'q-dinner-table': VM((o) => pdc(o.who, o.kid) + (o.time === 'night' ? 13 : 12), '夕飯 (models): a mum and her boy sit on cushions at a low table under a window where the sun sets; rice bowls and grilled fish pop onto the table; the boy puts his hands together: いただきます, lifts his bowl and eats with chopsticks; time night (晩御飯): moon and stars in the window, a lamp glows over the table, dumplings', (o) => [o.who, o.kid, 'rice', o.time === 'night' ? 'gyoza' : 'fishWhole'], { who: 'gal2', kid: 'guy2', time: 'sunset' }, 'time'),
  'q-soot-puff': VM((o) => pdc(o.who) + 4, '黒 (models): a chimney coughs a big black cloud down over a man; he comes out black all over, only his eyes white and blinking: まっくろ!; he shakes it off and is clean again', (o) => [o.who], { who: 'guy2' }),
  'q-frog-prince': VM((o) => pdc(o.who) + 4, '変 (models): a frog hops in; POOF, it is a prince in a kimono and a crown, who waves: へんしん!; POOF, a frog again; the kanji wobbles at each change', (o) => [o.who], { who: 'kimonoMan' }),
  'q-back-to-back': VM((o) => pdc(o.who, o.other) + 3, '背 (models): two children stand back to back at a height chart; a bar comes down on the taller one\'s head and the shorter one goes up on tiptoe: せいくらべ; they turn to us and wave', (o) => [o.who, o.other], { who: 'guy2', other: 'gal3' }),
  'q-room-expand': VM((o) => pdc(o.who) + 4, '広い (models): a girl stands squeezed in a narrow room, arms tucked in; the walls slide far apart; she spreads her arms wide and twirls: ひろい!', (o) => [o.who], { who: 'gal' }),
  'q-year-hop': VM((o) => pdc(o.who) + 6, '再来年 (models): three calendar blocks (いま, +1, +2); a boy hops two blocks ahead and cheers on the last, arms up: やった!', (o) => [o.who], { who: 'guy2' }),
};
