// Vignette catalog entries of the Step 3a model pass, batch 5 part a (spread into vignette-catalog.js).
import { VM, pdc } from './vcat-kit.js';

const kanaText = (o) => !!o.text && o.text !== '1+1=2';
export const Q5A = {
  'q-teach-board': VM((o) => pdc(o.who, o.kid) + 4 + (kanaText(o) ? [...o.text].length + 1 : 3), '教 (models): a teacher writes 1+1=2 on a blackboard with chalk, walking along under it; she turns to a small pupil, who shoots a hand up (はい!) as a lightbulb pops on over her; text (教える, あいう): she writes the text, taps each letter with the chalk and the pupil reads it out (あ! い! う!); a red はなまる pops up and the pupil cheers', (o) => [o.who, o.kid], { who: 'suitWoman', kid: 'gal2', text: null }, 'text'),
  'q-classroom-kids': VM((o) => pdc(o.who, o.other, o.third) + 3, '教室 (models): a blackboard (あいうえお) and three desks facing you; three small kids walk in one after another, turn round at their chairs and sit; all shoot a hand up (はい!), then stand and walk out', (o) => [o.who, o.other, o.third], { who: 'guy2', other: 'gal2', third: 'guy3' }),
  'q-school-bell': VM((o) => pdc(o.who, o.other, o.third) + 5, '校 (models): a school with a clock tower; its bell swings and rings (キンコーン) and three small kids run out of the door into the yard, jump for joy (わーい!) and run back in at the next bell; outcome kids (学校): with red school bags on their backs, three kids run in at the door from the street as the bell rings', (o) => [o.who, o.other, o.third], { who: 'gal2', other: 'guy2', third: 'gal', outcome: 'bell' }, 'outcome'),
  'q-office-tower': VM((o) => pdc(o.who, o.other) + (o.outcome === 'commute' ? 5 : 6), '社 (models): an office tower with a かいしゃ sign lights up floor by floor; in front of it two office workers face each other, bow and swap business cards held out in both hands (よろしく!); outcome commute (会社): the two walk in at its door one after the other, briefcases in hand, and the floors light up once they are in', (o) => [o.who, o.other], { who: 'suitMan', other: 'suitWoman', outcome: 'lights' }, 'outcome'),
  'q-police-box': VM((o) => pdc(o.who, o.kid) + 7, '交番 (models): a little police box (こうばん, a red lamp); a lost child walks up crying (えーん); the officer in a navy cap bends down to her and points the way with his whole arm (あっち!); she nods (ありがとう!) and walks off that way, waving', (o) => [o.who, o.kid], { who: 'worker', kid: 'gal' }),
  'q-library-shelf': VM((o) => pdc(o.who) + 6, '図書館 (models): a boy sits at a reading table under a tall bookshelf (としょかん); a red book slides out of its gap and floats over to him; it opens in his hands and he reads (しーん); then it shuts and floats back to its place', (o) => [o.who], { who: 'guy3' }),
  'q-shop-open': VM((o) => pdc(o.who) + 4 + (o.outcome === 'veg' || o.outcome === 'closed' ? 2 : 0), '屋 (models): a little shop with a striped awning (みせ): its shutter rolls up on the shopkeeper behind the counter, who waves you in (いらっしゃい!), and rolls down again; outcome veg (八百屋): crates of cabbages, tomatoes and carrots on the counter (やおや); he holds up a big daikon, then a carrot: やすいよ!; closed (閉まる): at dusk he waves goodbye (またね!) and the shutter rolls down by itself (ガラガラ); a へいてん sign swings on it', (o) => [o.who], { who: 'chef', outcome: 'open' }, 'outcome'),
  'q-shop-counter': VM((o) => pdc(o.who, o.other) + (o.outcome === 'cafe' ? 8 : 5), '店 (models): a market stall with a blue awning and a till; a woman walks up and pays a coin, the till drawer pops out (チン!) and the shopkeeper hands her a paper bag; she walks off with it; outcome cafe (喫茶店, who: the waiter): she sits at a café table (きっさてん); the waiter carries in a tray with a steaming coffee and a cake, sets them down and bows (どうぞ); she sips: hearts', (o) => [o.who, o.other], { who: 'worker', other: 'gal', outcome: 'stall' }, 'outcome'),
  'q-butler-door': VM((o) => (o.outcome === 'hardhat' ? pdc(o.who) + 6 : pdc(o.who, o.other) + 3), '仕 (models): a butler in a white shirt stands by a grand door; as a guest walks up he opens it, holds it by the edge and bows low, sweeping her in (どうぞ); she goes in, he shuts it and bows again; outcome hardhat (仕事, who: worker): a worker carries a long plank on his shoulder to two trestles, lays it across them, hammers it three times (トントン), then wipes his sweaty brow: よし!', (o) => (o.outcome === 'hardhat' ? [o.who] : [o.who, o.other]), { who: 'suitMan', other: 'gal', outcome: 'butler' }, 'outcome'),
  'q-hall-rise': VM((o) => pdc(o.who, o.other) + 1 + (({ embassy: 5, cinema: 4 })[o.outcome] ?? 0), '館 (models): a big columned hall on three steps rises out of the ground while the strokes draw; two visitors walk up, climb the steps and go in at its door; outcome embassy (大使館): a Japanese flag and a blue-white-red flag wave on poles either side, and at the foot of the steps the man holds his passport up (パスポート) before going in; cinema (映画館): an えいが marquee in a ring of chasing bulbs over the door, and the pair go in holding tubs of popcorn', (o) => [o.who, o.other], { who: 'guy', other: 'gal', outcome: 'hall' }, 'outcome'),
  'q-queue-number': VM((o) => pdc(o.who, o.other, o.third, o.clerk) + 4, '番 (models): three people queue at a counter under a number board; ピンポン, the board shows 1ばん and the front one steps up, takes a parcel from the clerk, bows and walks off, while the other two move up a place; he joins the back of the line, and the board counts on: 2ばん, 3ばん', (o) => [o.who, o.other, o.third, o.clerk], { who: 'guy', other: 'gal2', third: 'grandma', clerk: 'suitWoman' }),
};
