// Vignette catalog entries of the Step 3a model pass, batch 4 part b (spread into vignette-catalog.js).
import { VM, pdc } from './vcat-kit.js';

export const Q4B = {
  'q-map-read': VM((o) => pdc(o.who) + 3, '地図 (models): a man holds a map up in both hands, turns it upside down (?), turns it back, points the way (こっち!) and walks off with it', (o) => [o.who], { who: 'guy3' }),
  'q-lost-key': VM((o) => pdc(o.who) + 3, '無くす (models): a woman walks along; a gold key slips out of her pocket; she stops, pats her pockets (?) and looks back at it glinting on the ground', (o) => [o.who], { who: 'gal2' }),
  'q-empty-box': VM((o) => pdc(o.who) + 4, '無 (models): a child lifts a box off a stool, tips it to show its inside, turns it upside down and shakes it: only a puff of dust; he puts it back and shrugs: からっぽ', (o) => [o.who], { who: 'guy2' }),
  'q-errand-run': VM((o) => pdc(o.who, o.other) + 5, '用 (models): a mum hands her child a note (おねがい!); he runs off and comes back with a carton of milk (ただいま!), hands it to her: hearts', (o) => [o.who, o.other], { who: 'guy', other: 'gal' }),
  'q-apple-sell': VM((o) => (o.outcome === 'sold' ? pdc(o.who) + 2 : pdc(o.who, o.other) + 4), '売 (models): a stallholder behind a crate of apples (¥100) holds one up; a shopper walks up and pays a coin, he hands her the apple and she walks off with it; outcome sold: he shows off a TV for sale, a red SOLD stamp slams onto it and he cheers (売る)', (o) => (o.outcome === 'sold' ? [o.who] : [o.who, o.other]), { who: 'worker', other: 'gal3', outcome: 'apple' }, 'outcome'),
  'q-memory-bubble': VM((o) => pdc(o.who) + 6, '覚 (models): a man on a stool reads; pictures (a star, an apple, a heart) float up out of the book into a thought bubble over his head and stay; he looks up at them and nods; outcome cards: he holds up flashcards one by one, each flies into his head, a bulb lights: おぼえた! (覚える)', (o) => [o.who], { who: 'guy', outcome: 'bubble' }, 'outcome'),
  'q-letter-blocks': VM((o) => pdc(o.who) + 1 + [...(o.letters ?? 'あいう')].length, '字 (models): letter blocks drop into a row; a child points at each in turn and it hops; letters: what the blocks show (漢字: 山川木)', (o) => [o.who], { who: 'gal', letters: null }, 'letters'),
  'q-study-desk': VM((o) => pdc(o.who) + 6, '勉強 (models): a child at a desk with a lamp and books writes line after line; a test pops up, 100 in a red circle, and he throws his arms up', (o) => [o.who], { who: 'guy3' }),
  'q-office-work': VM((o) => (o.outcome === 'class' ? pdc(o.who, o.kid, o.other) + 7 : pdc(o.who) + 6), '業 (models): an office worker types at a laptop (カタカタ); finished papers stack up beside her while the wall clock spins; outcome class: a teacher writes on the blackboard in front of two pupils at their desks, the bell rings (キーンコーン) and the pupils put their hands up (授業)', (o) => (o.outcome === 'class' ? [o.who, o.kid, o.other] : [o.who]), { who: 'suitWoman', kid: 'guy2', other: 'gal2', outcome: 'office' }, 'outcome'),
  'q-juggle-crash': VM((o) => pdc(o.who) + 3, '大変 (models): a man juggles plates, more and more of them, wobbling, until they all crash down (ガシャーン!) and he clutches his head', (o) => [o.who], { who: 'guy3' }),
  'q-mask-off': VM((o) => pdc(o.who) + 3, '本当 (models): a man in a disguise (glasses, big nose, moustache) glances about (?); he pulls it off, it flies away and he smiles: a green check', (o) => [o.who], { who: 'guy' }),
  'q-practice-kick': VM((o) => pdc(o.who) + 3, '練習 (models): a child kicks a ball at a wall again and again; it bounces back each time and a chalk tally mark goes up on the wall', (o) => [o.who], { who: 'guy2' }),
};
