// Vignette catalog entries of the Step 3a model pass, batch 5 part b (spread into vignette-catalog.js).
import { VM, pdc } from './vcat-kit.js';

const actorOf = (o) => o.who ?? (o.outcome === 'open' ? 'kimono' : 'kimonoMan');
const RUN3 = ['gal2', 'guy', 'guy3'], POD3 = ['guy2', 'gal', 'guy3'], KIDS5 = ['guy2', 'gal2', 'guy3', 'gal', 'guy'];

export const Q5B = {
  'q-race-win': VM(pdc(...RUN3) + 6, '一番 (models): three runners race toward you down a track; the first breaks the finish tape, throws her arms up (Victory) and a gold 1 medal pops over her head; the other two arrive and pant, hands on knees', RUN3),
  'q-podium-win': VM(pdc(...POD3) + 7, '最 (models): three children hop up onto a podium (2 1 3); each gets a trophy, small, medium and, for the winner on the top step, a huge one that he lifts over his head while the other two clap', POD3),
  'q-race-start': VM(pdc('gal3', 'guy2') + 6, '始 (models): two runners lean ready at the start line (よーい…); the flag drops (ドン!) and they dash off in a puff of dust', ['gal3', 'guy2']),
  'q-curtain-close': VM((o) => pdc(actorOf(o)) + (o.outcome === 'open' ? 6 : 5), '終 (models): an actor in kimono bows on a little stage; the red curtains slide shut and おわり appears on them; outcome open: the curtains part, the spotlight comes up, confetti falls and an actress in kimono steps forward and waves: はじまり! (始まる)', (o) => [actorOf(o)], { who: null, outcome: 'close' }, 'outcome'),
  'q-line-up': VM(pdc(...KIDS5) + 1, '並 (models): five children run in from the back and line up shoulder to shoulder on a chalk line, then bow together; outcome height: they walk in one by one and queue one behind another facing the kanji, smallest to tallest, and shuffle forward (並ぶ)', KIDS5, { outcome: 'row' }, 'outcome'),
  'q-travel-road': VM((o) => (o.outcome === 'suitcase' ? pdc(o.who ?? 'gal') + 6 : pdc(o.who ?? 'gal3') + 6), '旅 (models): a hiker with a backpack sets off from her little house along a winding path that recedes into the distance (the land tilted toward you), turns at a signpost to wave bye-bye and walks on toward far mountains and the sun, smaller and smaller, until she is gone; outcome suitcase: she pulls a rolling suitcase along; Fuji, a torii and a tower pop up one after another, she turns to you for a holiday snap (V sign, パシャ!) and its sticker slaps onto the case (旅行)', (o) => [o.who ?? (o.outcome === 'suitcase' ? 'gal' : 'gal3')], { who: null, outcome: 'walk' }, 'outcome'),
  'q-move-in': VM((o) => (o.outcome === 'crab' ? 3 : pdc(o.who ?? 'guy2') + 8), '住 (models): a man carries a moving box from the stack by the path in at the door of a house; the light comes on, the chimney smokes and he waves from the window, a heart over the roof; outcome crab: a hermit crab climbs into an empty shell and peeks out of its new home (kit scene, 住む)', (o) => (o.outcome === 'crab' ? [] : [o.who ?? 'guy2']), { who: null, outcome: 'house' }, 'outcome'),
  'q-home-greet': VM((o) => (o.outcome === 'bird' ? 7 : pdc(o.who ?? 'suitMan', o.kid ?? 'gal') + 11), '帰 (models): at dusk a man with a briefcase walks up to his lit house: ただいま!; the door opens, light spills out and his little girl runs out and hugs him: おかえり!, hearts; they go in together and the door shuts; outcome bird: a mother bird flies home to her nest with a worm, the chicks bounce (kit scene, 帰る)', (o) => (o.outcome === 'bird' ? [] : [o.who ?? 'suitMan', o.kid ?? 'gal']), { who: null, kid: null, outcome: 'house' }, 'outcome'),
  'q-house-build': VM((o) => pdc(o.who ?? 'guy') + 5, '家 (models): a house builds itself beside the kanji, the walls rise and the roof drops on; a man walks home, in at the door, the window lights up and the chimney smokes', (o) => [o.who ?? 'guy'], { who: null }),
  'q-inn-sleep': VM((o) => pdc(o.who ?? 'guy3') + 11, '宿 (models): a traveller with a suitcase walks up to an inn (やど sign, a lantern, a noren curtain), bows and goes in; he yawns at the lit window, the light goes out and Zzz float up under the moon', (o) => [o.who ?? 'guy3'], { who: null }),
  'q-my-room': VM((o) => pdc(o.who ?? 'gal2') + 8, '部屋 (models): an empty room fills up one thing at a time (a teddy, bed, desk and chair, lamp, poster); a little girl walks in, looks round and jumps for joy: やったー!, hearts', (o) => [o.who ?? 'gal2'], { who: null }),
  'q-toilet-dash': VM((o) => pdc(o.who ?? 'guy3') + 10, 'お手洗い (models): a man hops from foot to foot by a WC door (!!), dashes in, ジャー, strolls out relieved (ふう〜) and washes his hands at the sink, shaking them dry', (o) => [o.who ?? 'guy3'], { who: null }),
};
