// Vignette catalog entries of the Step 3a model pass, batch 5 part c (spread into vignette-catalog.js).
import { VM, pdc } from './vcat-kit.js';

export const Q5C = {
  'q-bus-ride': VM((o) => pdc(o.who) + (o.outcome === 'bike' ? 3 : 6), '乗 (gal2): a girl waits at a bus stop (バス); a green bus comes up the road and pulls in, the door folds open, she climbs in, sits at a window and waves out of it as the bus drives off; outcome bike (guy, a child): he walks up to his bicycle, hops up onto the saddle (よいしょ!), waves and pedals off (乗る)', (o) => [o.who], { who: 'gal2', outcome: 'bus' }, 'outcome'),
  'q-bus-off': VM((o) => pdc(o.who) + 5, '降りる (guy): an orange bus pulls in with a man sitting at a window; he stands up, the door folds open and he steps out and hops down onto the pavement (ぴょん), waves the bus off and walks away', (o) => [o.who], { who: 'guy' }),
  'q-bike-bell': VM((o) => pdc(o.who) + 4, '自転車 (guy2, a teen): a boy rides a big red bicycle round and round in front of you, pedalling, and rings the bell each time he passes: チリンチリン!', (o) => [o.who], { who: 'guy2' }),
  'q-train-arrive': VM((o) => pdc(o.who) + 8, '着く (tramCar, gal): a train glides into the station and stops at the platform; its doors slide open, a woman steps out, turns to you and waves: ついた!; she walks off, the doors shut and the train pulls out', (o) => ['tramCar', o.who], { who: 'gal' }),
  'q-subway-cut': VM((o) => pdc(o.who) + 11, '地下鉄 (tramCar, guy): the street is cut open like a cake: a man walks along the road on top while a two-car train rattles through the tunnel underneath (ガタンゴトン); he stops and looks down at his feet as it passes, and walks on', (o) => ['tramCar', o.who], { who: 'guy' }),
  'q-stop-sign': VM((o) => (o.outcome === 'car' ? 11 : pdc(o.who) + 6), '止 (guy2): a man runs up to a 止まれ sign and skids to a stop at the line, arms windmilling, dust flying (!), stands, nods and walks back; outcome car (sedan): a car drives up the street and brakes hard at the stop line under the sign (キキーッ!), waits, then turns into the side street and drives away (止まる)', (o) => (o.outcome === 'car' ? ['sedan'] : [o.who]), { who: 'guy2', outcome: 'run' }, 'outcome'),
  'q-pin-drop': VM((o) => pdc(o.who) + 5, '所 (gal3): a giant map pin drops out of the sky onto a little map and sticks in, rings pulsing out; a woman runs over to the spot, jumps and waves: ここ!', (o) => [o.who], { who: 'gal3' }),
  'q-knock-door': VM((o) => (o.outcome === 'window' ? pdc(o.other) + 4 : pdc(o.who, o.other) + 5), '誰 (gal2, guy as a shadow): a girl knocks on a house door (コンコン); it opens a crack and a shadowy figure with glowing eyes leans out under a big "?"; she jumps back; it slips back in and the door shuts; outcome window: at night a shadowy figure walks past a lit window behind the wall, stops, turns and peers out at you (?), then walks on (誰か)', (o) => (o.outcome === 'window' ? [o.other] : [o.who, o.other]), { who: 'gal2', other: 'guy', outcome: 'door' }, 'outcome'),
  'q-merry-go-round': VM((o) => pdc(o.who, o.other) + 4, '楽しい (gal, guy2 as children): two children ride a merry-go-round, one hand on the pole; the horses bob up and down as it turns, they wave as they come round the front and cheer (わーい!), notes float up', (o) => [o.who, o.other], { who: 'gal', other: 'guy2' }),
  'q-beach-day': VM((o) => pdc(o.who) + 7, '夏休み (gal, a child): under the summer sun a girl in a pink swim ring bobs on the waves; she bats a beach ball up, it splashes down and drifts back to her; a red beach umbrella on the sand', (o) => [o.who], { who: 'gal' }),
  'q-rest-day': VM((o) => pdc(o.who) + (o.outcome === 'bed' ? 9 : 5), '休み (guy): a man swings in a hammock between two palm trees in the sun, hands behind his head, humming (のんびり〜); outcome bed (gal3): a girl ill in bed with a thermometer (38°) sits up, phones in sick (やすみます…), lies back down and sleeps, Zzz (休む)', (o) => [o.who], { who: 'guy', outcome: 'holiday' }, 'outcome'),
};
