// Vignette catalog entries of the Step 3a model pass, batch 4 part a (spread into vignette-catalog.js).
import { VM, pdc } from './vcat-kit.js';

export const Q4A = {
  'q-coat-on': VM((o) => pdc(o.who) + 3 + (o.outcome === 'jacket' ? 4 : o.outcome === 'wear' ? 0 : 2), '着 (suitWoman): she walks in and stops on a doormat: ついた! (arrive); a red coat drops onto her, she tugs it straight and twirls (wear); outcome wear: a blue coat drops on and she does the buttons up one by one (着る); jacket: shivering in the snow (さむい…), she lifts a green jacket off a coat stand, swings it on and hugs herself warm: ぽかぽか (上着)', (o) => [o.who], { who: 'suitWoman', outcome: 'arrive', color: null }, 'outcome'),
  'q-wardrobe-dress': VM((o) => pdc(o.who) + 6, '服 (gal3): a wardrobe opens; a red shirt flies onto a woman in plain grey, then blue trousers, and her clothes turn those colours; she twirls to show them off', (o) => [o.who], { who: 'gal3' }),
  'q-suit-up': VM((o) => pdc(o.who) + 2, '背広 (suitMan): a man in a suit straightens his tie (a sparkle), picks up his briefcase and walks off to work', (o) => [o.who], { who: 'suitMan' }),
  'q-shoe-step': VM((o) => pdc(o.who) + 3, '靴 (gal2, a child): a pair of red shoes hops onto a mat; she steps into them, looks down, hops and walks off in them; outcome socks: striped pink socks (靴下)', (o) => [o.who], { who: 'gal2', outcome: 'shoes' }, 'outcome'),
  'q-paper-fold': VM((o) => pdc(o.who) + (o.outcome === 'letter' ? 5 : 4), '紙 (guy2, a child): a sheet of paper flutters down in front of him, folds into a triangle, again, and becomes a paper hat that hops onto his head: わあ!; outcome letter (gal): she writes a letter on a sheet in her hand, it folds into an envelope sealed with a heart, she holds it up and it flaps off like a bird while she waves (手紙)', (o) => [o.who], { who: 'guy2', outcome: 'hat' }, 'outcome'),
  'q-shop-basket': VM((o) => pdc(o.who) + 6, '買い物 (gal2): a woman with a basket walks along a shop shelf; an apple, a milk carton and a loaf hop off it into her basket; she lifts the full basket: いっぱい!', (o) => [o.who], { who: 'gal2' }),
  'q-luggage-pile': VM((o) => pdc(o.who) + 3, '荷物 (guy3): a man staggers in carrying a tall pile of bags and cases; the top one teeters and he sways to save it (おっとっと), then staggers off again', (o) => [o.who], { who: 'guy3' }),
  'q-hug-treasure': VM((o) => pdc(o.who) + 5, '大切 (guy2): a treasure chest opens on a glowing gem; a man lifts it out, hugs it to his chest and sways, hearts rising; he lays it back and the lid shuts', (o) => [o.who], { who: 'guy2' }),
  'q-hand-over': VM((o) => pdc(o.who, o.other) + 2, '渡す (worker, gal): a worker holds out a parcel in both hands and carries it across to a woman, who takes it and bows: ありがとう', (o) => [o.who, o.other], { who: 'worker', other: 'gal' }),
  'q-rope-pull': VM((o) => pdc(o.who) + 3, '引 (worker): a rope is tied to the kanji; a worker leans back and hauls it toward him in three heaves (よいしょ!), dust puffing, then it slides home; outcome drawer: he grips the knob of a chest of drawers, leans back and pulls out a drawer full of toys (引く)', (o) => [o.who], { who: 'worker', outcome: 'rope' }, 'outcome'),
  'q-boomerang-throw': VM((o) => (o.outcome === 'book' ? pdc(o.who, o.other) + 3 : pdc(o.who) + 3), '返 (guy2): a man throws a boomerang; it swings out in a wide loop, spinning, and comes back to his hand: おかえり!; outcome book (a child and a librarian): the child holds a book out over a library counter, the librarian takes it (ありがとう) and lays it on the pile; the child bows (返す)', (o) => (o.outcome === 'book' ? [o.who, o.other] : [o.who]), { who: 'guy2', other: 'suitWoman', outcome: 'boomerang' }, 'outcome'),
  'q-photo-snap': VM((o) => pdc(o.who) + 6, '写 (gal): she makes a peace sign at a camera on a tripod; flash; a photo slides out, rises and develops into a little picture of her; outcome wall: a camera at her eye, flash by flash three photos fly up and pin themselves to a cork board (写真)', (o) => [o.who], { who: 'gal', outcome: 'camera' }, 'outcome'),
};
