// The "vignette" slot's catalog: every scene type, its options (with defaults) and the draw calls it builds. Pure data, no
// three.js (Node scripts import it through catalog.js). Implementations: src/effects/vignettes/ (one module per theme).
// Every vignette also takes `at` ([x, y] offset of its actors in glyph heights) and `size` (scale of its actors, about the
// kanji's bottom-right corner: scenes that act on the kanji itself should keep it 1).
// A vignette uses no particle slots and no lights of its own; draw calls must equal what it builds (npm run e2e checks).
//   variant: the option that tells two uses of one type apart (上手 / 下手: one set-up, two outcomes)
const V = (dc, desc, opts = {}, variant = null) => ({ dc, desc, opts: { at: null, size: null, ...opts }, variant });

export const VIGNETTES = {
  'hammer-nail': V(10, 'a hand swings a hammer at a nail standing in a board; outcome clean: three blows drive it in flush, a sparkle, thumbs up (skilled); bend: the nail bends over, the hammer hits the thumb, stars (unskilled)', { outcome: 'clean' }, 'outcome'),
  push: V(3, 'a person walks up beside the kanji, leans in and shoves it along in three heaves, dust puffing where it scrapes (push); dir: the way it is pushed (left: they stand on its right)', { dir: 'left' }),
  'lift-heavy': V(4, 'a person squats, grips the kanji and strains (shaking, sweat flying); it barely lifts and thuds down, knocking them onto their bottom (heavy)'),
  'come-near': V((o) => (o.outcome === 'face' ? 2 : 3), 'a person far down a path walks towards you, growing, until they stand right beside the kanji and lean in close (near); outcome face: they step and lean towards you until their face is right up close (close)', { outcome: 'walk' }, 'outcome'),
  'stack-plates': V((o) => (o.outcome === 'dry' ? 7 : 2), 'the kanji is the stand: plates fly in and stack on it with a clink, the top one wobbles, a cake lands on it (dish, plate); outcome dry: a hand wipes a wet plate until it gleams and sets it on the pile', { outcome: 'stack' }, 'outcome'),
  'odd-one-out': V(4, 'a row of identical blue balls bounces along in step; one is red and square and hops out of time; a magnifier finds it, a cross pops up (different, wrong)'),
  'hand-in-hand': V(5, 'two people walk in from either side, meet in front of the kanji, take hands and swing them, hearts rising (two people, a couple)'),
  'box-tumble': V(9, 'a box beside the kanji pops its flaps; things tumble out one after another (ball, cup, apple, shoe) into a heap, the last one bonking the kanji; they hop back in (thing, things)'),
  'house-build': V(7, 'a wall rises behind the kanji, a roof drops on, the chimney smokes; a person walks home, goes in the door and the window lights up (house, home)'),
  'scrub-wash': V(8, 'mud splats onto the kanji; a hand scrubs it with a sponge, foam builds, a bucket tips water over it and it sparkles (wash)'),
  'tea-pour': V(6, 'tea leaves drop into a teapot, it rattles, tips and pours a green stream into a cup that fills and steams (tea); outcome serve: the cup slides forward to you on its saucer with a bow (tea, served)', { outcome: 'pour' }, 'outcome'),
  'rice-bowl': V(6, 'rice plops into a bowl in heaps and steams; chopsticks dip in and lift clumps away until it is empty (meal, rice)'),
  'sunset-lights': V(6, 'the sun sinks behind a hill with little houses, dusk falls, their windows light up one by one, the moon rises, stars come out (nightfall, evening)'),
  'calendar-back': V((o) => 3 + (o.days ?? 1), 'a calendar shows today; its page flips back a day (days 2: two) while a little sun runs backwards across the sky (yesterday)', { days: 1 }, 'days'),
  'go-to-bed': V(10, 'a person yawns, lies down on a futon and pulls up the blanket; dusk falls, the moon rises, stars twinkle, Zzz floats up (night)'),
  'noon-sun': V((o) => (o.outcome === 'eat' ? 4 : 7), 'the sun climbs from the horizon to straight overhead, the person looking up after it; at the top it flares, they cheer and open their lunchbox (noon, daytime); outcome eat: they sit and eat a rice ball under it (lunch)', { outcome: 'rise' }, 'outcome'),
  'chop-split': V((o) => (o.food ? 4 : 2), 'a cleaver chops straight down through the middle of the kanji; a flash along the cut and the halves slide apart, then back (cut); food carrot: a carrot on a board chopped into rounds (to cut)', { food: null }, 'food'),
  'todo-list': V(4, 'a pencil ticks the three boxes of a to-do list one by one; the list spins round and starts again (matter, things to do)'),
  'pin-drop': V(5, 'a big map pin drops from the sky and stabs into the ground beside the kanji, a ring pulsing out; a person runs over and waves from the spot (place)'),
  'dart-bullseye': V(5, 'darts fly from where you stand into the bullseye of a target one by one; it wobbles, a ding (hit, correct)'),
  'apple-ripen': V(4, 'a green apple on a branch ripens yellow then red, swells, sparkles and drops; a new one grows (red)'),
  'eraser-rub': V(4, 'a hand rubs the strokes out one by one with an eraser, crumbs falling; then they write back in (erase)'),
  'wheels-roll': V(4, 'wheels pop out under the kanji, it revs with puffs of exhaust and drives off to the right, then back (move)'),
  'coat-on': V((o) => (o.outcome === 'jacket' ? 5 : 4), 'a person walks in and stops on a mat beside the kanji (arrive); a coat drops onto them, the sleeves slide down, they tug it straight and twirl (wear); outcome wear: the buttons done up one by one (to wear); jacket: lifted off a stand and swung on (jacket)', { outcome: 'arrive', color: null }, 'outcome'),
  'mirror-me': V(6, 'a person in front of a standing mirror; their face looks back from the glass; they point at their own nose (the Japanese "me"), the reflection too, a sparkle (oneself)'),
  'big-brother': V((o) => (o.outcome === 'piggyback' ? 4 : 5), 'a big kid holds a ball up high while a small one hops for it; he laughs, hands it down and pats the small one\'s head (older brother); outcome piggyback: carries the small one on his back', { outcome: 'ball' }, 'outcome'),
  'teach-board': V(9, 'a teacher writes 1+1=2 on a blackboard, tapping with a pointer; a small pupil shoots a hand up and a lightbulb pops on (teach); text: what is written', { text: null }, 'text'),
  'queue-number': V(8, 'three people queue at a counter under a number sign; it counts 1, 2, 3 and each time the front one is served and walks off, the rest shuffle up (turn, number)'),
  'which-way': V(4, 'a person by a signpost looks one way, then the other, scratching their head; the sign\'s arm swings round to point and off they walk (direction, way)'),
  'drum-fun': V(5, 'a kid drums on top of the kanji with two sticks; it squashes with every beat and music notes fly up (fun, music)'),
  'leaf-fall': V(3, 'a branch reaches out from the kanji, a bud unfurls into a big leaf that flutters, lets go and zigzags down to the ground (leaf)'),
  'gust-hat': V(5, 'a gust blows across: the kanji leans over, a person leans into it and their hat flies off tumbling away; the wind drops and a new hat lands (wind)'),
  'food-row': V(4, 'three plates slide in, each with a food (a rice ball, a fish, an apple); a fork stabs the fish and lifts it away (food)'),
  'fruit-bowl': V(5, 'an apple, a banana and a bunch of grapes drop one by one into a bowl and settle (fruit)'),
  'drink-straw': V(4, 'a straw drops into a glass of juice and the level goes down with rising bubbles (slurp); it refills (drink)', { color: null }),
  toaster: V(5, 'two slices of toast pop up high out of a toaster and land; an egg fries in a pan beside it (breakfast)'),
  teabag: V(4, 'a teabag dunks into a cup of hot water three times and the red-brown colour spreads; steam (black tea)'),
  'bowl-spin': V(3, 'clay spins on a potter\'s wheel and rises into a bowl, then turns glaze blue (bowl)'),
  'bento-open': V(3, 'a lunchbox lid lifts off: rice, an egg roll, a sausage; chopsticks pick something out (lunch box)'),
  ashtray: V(3, 'a cigarette is stubbed out in a dish; a curl of smoke rises and fades (ashtray)'),
  'shop-basket': V(7, 'a person with a basket walks along a shelf of goods and things hop off the shelf into the basket (shopping)'),
  'luggage-pile': V(4, 'a person staggers in under a tall pile of bags and cases, the top one teetering (luggage)'),
  'hug-treasure': V(6, 'a treasure chest opens on a glowing gem; a person hugs the chest tight, hearts rising (important, precious)'),
  'hand-wash': V(7, 'two hands rub together under a running tap, suds foaming, then shake dry (wash)'),
  laundry: V(5, 'clothes tumble round in a washing machine\'s window; it stops and shirts hop out onto a line and flap (laundry)'),
  'toilet-dash': V(5, 'a person hops from foot to foot by a door marked WC, dashes in, the door shuts; it opens and they stroll out relieved (toilet)'),
  'switch-off': V(8, 'a finger flicks a switch: the lamp goes out and it goes dark; flick, it comes back (turn off, erase)'),
  'candle-out': V(3, 'a candle flame flickers, shrinks and goes out by itself, a curl of smoke; it lights again (disappear)'),
  'gift-open': V(5, 'a wrapped present shakes, its flaps fly open and a star pops out spinning (open)'),
  'bath-tub': V(6, 'a person relaxes in a bathtub, bubbles rising, a rubber duck bobbing, steam (bath)'),
  sneeze: V(5, 'a person with a red nose: ah... ah... CHOO! a spray bursts out, a tissue flies, they shiver (a cold)'),
  'ticket-gate': V(7, 'a ticket slides out of a machine, a hand takes it, the gate\'s flaps swing open (ticket)'),
  'stamp-letter': V(5, 'a stamp flies onto the corner of an envelope with a thump, then a postmark stamps over it (postage stamp)'),
  'train-arrive': V(5, 'a train glides in along the platform and stops; a person steps off and waves (arrive)'),
  'car-park': V(4, 'a car drives in by itself and backs into a parking space, beep beep (car)'),
  'traffic-red': V(6, 'a traffic light changes green, yellow, RED; a car rolling up stops (red)'),
  neighbourhood: V(3, 'a house; little houses pop up all round it and a dotted ring draws around them (neighbourhood, nearby)'),
  'postcard-post': V(3, 'a postcard with a mountain picture flips over, lines write on its back, and it flies into a red postbox (postcard)'),
  'button-press': V(5, 'a finger presses a big red button down; it lights up and dings (push, press)'),
  keypad: V(5, 'a finger taps a number on a keypad, each key lighting up; the number appears on the screen (number)', { number: null }),
  'family-wave': V(7, 'a dad, a mum and a small kid walk out together and stand in a row waving, hearts over them (family)'),
  'animal-parade': V(9, 'a cow plods by, a bird flaps over it, a snail creeps after them (animal)'),
  'me-spotlight': V(9, 'three people; a "?" pops up; one steps forward, hand on their chest, and a spotlight lands on them (myself)'),
  'mask-off': V(5, 'a person in a funny disguise (big glasses and nose); it pops off and flies away, they smile and a green check pops up (truth, real)'),
  'classroom-kids': V(8, 'a blackboard and three desks; three kids file in and sit down at them (classroom)'),
  'talk-bubbles': V((o) => 4 + (o.words?.length ?? 3), 'two people chat; speech bubbles rise between them in different languages (language, words)', { words: null }),
  'merry-go-round': V(9, 'kids ride round and round on a merry-go-round, bobbing, notes flying (fun)'),
  'race-win': V(10, 'three runners race to a tape; the first breaks it, throws their arms up and a gold 1 pops (first, number one)'),
  'drag-suitcase': V(5, 'a person drags a huge suitcase that barely moves, leaning hard, sweat flying, then flops onto it (heavy)'),
  'spot-difference': V(3, 'two pictures side by side, almost the same; a red ring draws round the one thing that differs (differ)'),
  'confetti-shapes': V(5, 'shapes of every colour and kind pop out one after another and swirl round (various)'),
  'paint-pour': V(3, 'a can tips and paint pours over a white teddy bear, colouring it (brown; color: the paint)', { color: null }),
  'rewind-clock': V(6, 'a clock beside the kanji: its hands spin backwards, a rewind sign flashes and a little sun runs back across the sky (yesterday, previous)'),
  'ground-thud': V(6, 'the kanji hops up and slams down onto a strip of earth: cracks shoot out, grass springs up and a mole pokes its head out (ground, earth)'),
  'lid-fit': V(1, 'the top of the kanji lifts off like a lid, hovers and drops back onto the box below with a click, a sparkle (fit, join)'),
  'gate-shut': V(2, 'the two halves of the kanji (門) slide together over the middle, clunk, a padlock snaps on; then it opens again (close, shut)'),
  'kanji-wings': V(2, 'the kanji sprouts two wings, flaps, lifts off, flies up and round, then glides back down to land (fly)'),
  'scroll-write': V(4, 'a scroll unrolls beside the kanji and a brush writes a line of characters along it (writing, sentence)', { text: null }, 'text'),
  'frog-prince': V(5, 'a frog hops onto the kanji, POOF, a prince with a crown; POOF, a frog again; the kanji wobbles (change, strange)'),
  'rope-pull': V(4, 'a person with a rope tied to the kanji leans back and hauls it towards them in three heaves (pull)'),
  'stop-sign': V(6, 'a person runs up to a stop sign (止まれ) and skids to a dead stop, arms windmilling, dust flying (stop)'),
  'refuse-spoon': V(5, 'a hand offers a kid a spoonful of greens; the kid turns away, arms crossed, shaking their head (dislike)'),
  'taste-spoon': V(7, 'a person dips a spoon into a steaming pot, tastes and lights up: mm! a sparkle, a belly rub (taste, flavour)'),
  'shiver-frost': V(6, 'frost creeps over the kanji and an icicle grows under it, dripping; a person beside it hugs themselves and shivers, breath puffing (cold)'),
  'sister-help': V(5, 'a big girl kneels and ties a little one\'s shoelace (a bow pops), then takes their hand and leads them along (older sister)'),
  'little-follow': V(4, 'a big kid walks on; a little one hurries after, bouncing; the big one waits with a hand out and they go on together (younger brother)'),
  'line-up': V(11, 'five kids run in from both sides and line up shoulder to shoulder on a line, then all bow together (line up, row)'),
  'sing-mic': V(6, 'a person on a little stage sings into a microphone, swaying, notes pouring out, an arm flung up at the end (sing, song)'),
  kit: V(21, 'review sheet of the props kit: hand poses, a person walking, hammer, nail, board, plate, ball, heart, burst (not for cards)', { pose: 'all' }),
};
