// The "vignette" slot's catalog: every scene type, its options (with defaults) and the draw calls it builds. Pure data, no
// three.js (Node scripts import it through catalog.js). Implementations: src/effects/vignettes/ (one module per theme).
// Every vignette also takes `at` ([x, y] offset of its actors in glyph heights) and `size` (scale of its actors, about the
// kanji's bottom-right corner: scenes that act on the kanji itself should keep it 1).
// A vignette uses no particle slots and no lights of its own; draw calls must equal what it builds (npm run e2e checks).
//   variant: the option that tells two uses of one type apart (上手 / 下手: one set-up, two outcomes)
const V = (dc, desc, opts = {}, variant = null) => ({ dc, desc, opts: { at: null, size: null, ...opts }, variant });

export const VIGNETTES = {
  'hammer-nail': V(10, 'a hand swings a hammer at a nail standing in a board; outcome clean: three blows drive it in flush, a sparkle, thumbs up (skilled); bend: the nail bends over, the hammer hits the thumb, stars (unskilled)', { outcome: 'clean' }, 'outcome'),
  push: V(3, 'a person walks up beside the kanji, leans in and shoves it along in three heaves, dust puffing where it scrapes (push); dir: the way it is pushed (left: they stand on its right)', { dir: 'left' }),
  'lift-heavy': V(4, 'a person squats, grips the kanji and strains (shaking, sweat flying); it barely lifts and thuds down, knocking them onto their bottom (heavy)'),
  'come-near': V((o) => (o.outcome === 'face' ? 2 : 3), 'a person far down a path walks towards you, growing, until they stand right beside the kanji and lean in close (near); outcome face: they step and lean towards you until their face is right up close (close)', { outcome: 'walk' }, 'outcome'),
  'stack-plates': V((o) => (o.outcome === 'dry' ? 7 : 2), 'the kanji is the stand: plates fly in and stack on it with a clink, the top one wobbles, a cake lands on it (dish, plate); outcome dry: a hand wipes a wet plate until it gleams and sets it on the pile', { outcome: 'stack' }, 'outcome'),
  'odd-one-out': V(4, 'a row of identical blue balls bounces along in step; one is red and square and hops out of time; a magnifier finds it, a cross pops up (different, wrong)'),
  'hand-in-hand': V(5, 'two people walk in from either side, meet in front of the kanji, take hands and swing them, hearts rising (two people, a couple)'),
  'box-tumble': V(9, 'a box beside the kanji pops its flaps; things tumble out one after another (ball, cup, apple, shoe) into a heap, the last one bonking the kanji; they hop back in (thing, things)'),
  'house-build': V(7, 'a wall rises behind the kanji, a roof drops on, the chimney smokes; a person walks home, goes in the door and the window lights up (house, home)'),
  'scrub-wash': V(8, 'mud splats onto the kanji; a hand scrubs it with a sponge, foam builds, a bucket tips water over it and it sparkles (wash)'),
  'tea-pour': V(6, 'tea leaves drop into a teapot, it rattles, tips and pours a green stream into a cup that fills and steams (tea); outcome serve: the cup slides forward to you on its saucer with a bow (tea, served)', { outcome: 'pour' }, 'outcome'),
  'rice-bowl': V(6, 'rice plops into a bowl in heaps and steams; chopsticks dip in and lift clumps away until it is empty (meal, rice)'),
  'sunset-lights': V(6, 'the sun sinks behind a hill with little houses, dusk falls, their windows light up one by one, the moon rises, stars come out (nightfall, evening)'),
  'calendar-back': V((o) => 3 + (o.days ?? 1), 'a calendar shows today; its page flips back a day (days 2: two) while a little sun runs backwards across the sky (yesterday)', { days: 1 }, 'days'),
  'go-to-bed': V(10, 'a person yawns, lies down on a futon and pulls up the blanket; dusk falls, the moon rises, stars twinkle, Zzz floats up (night)'),
  'noon-sun': V((o) => (o.outcome === 'eat' ? 4 : 7), 'the sun climbs from the horizon to straight overhead, the person looking up after it; at the top it flares, they cheer and open their lunchbox (noon, daytime); outcome eat: they sit and eat a rice ball under it (lunch)', { outcome: 'rise' }, 'outcome'),
  'chop-split': V((o) => (o.food ? 4 : 2), 'a cleaver chops straight down through the middle of the kanji; a flash along the cut and the halves slide apart, then back (cut); food carrot: a carrot on a board chopped into rounds (to cut)', { food: null }, 'food'),
  'todo-list': V(4, 'a pencil ticks the three boxes of a to-do list one by one; the list spins round and starts again (matter, things to do)'),
  'pin-drop': V(5, 'a big map pin drops from the sky and stabs into the ground beside the kanji, a ring pulsing out; a person runs over and waves from the spot (place)'),
  'dart-bullseye': V(5, 'darts fly from where you stand into the bullseye of a target one by one; it wobbles, a ding (hit, correct)'),
  'apple-ripen': V(4, 'a green apple on a branch ripens yellow then red, swells, sparkles and drops; a new one grows (red)'),
  'eraser-rub': V(4, 'a hand rubs the strokes out one by one with an eraser, crumbs falling; then they write back in (erase)'),
  'wheels-roll': V(4, 'wheels pop out under the kanji, it revs with puffs of exhaust and drives off to the right, then back (move)'),
  'coat-on': V((o) => (o.outcome === 'jacket' ? 5 : 4), 'a person walks in and stops on a mat beside the kanji (arrive); a coat drops onto them, the sleeves slide down, they tug it straight and twirl (wear); outcome wear: the buttons done up one by one (to wear); jacket: lifted off a stand and swung on (jacket)', { outcome: 'arrive', color: null }, 'outcome'),
  'mirror-me': V(6, 'a person in front of a standing mirror; their face looks back from the glass; they point at their own nose (the Japanese "me"), the reflection too, a sparkle (oneself)'),
  'big-brother': V((o) => (o.outcome === 'piggyback' ? 4 : 5), 'a big kid holds a ball up high while a small one hops for it; he laughs, hands it down and pats the small one\'s head (older brother); outcome piggyback: carries the small one on his back', { outcome: 'ball' }, 'outcome'),
  'teach-board': V(9, 'a teacher writes 1+1=2 on a blackboard, tapping with a pointer; a small pupil shoots a hand up and a lightbulb pops on (teach); text: what is written', { text: null }, 'text'),
  'queue-number': V(8, 'three people queue at a counter under a number sign; it counts 1, 2, 3 and each time the front one is served and walks off, the rest shuffle up (turn, number)'),
  'which-way': V(4, 'a person by a signpost looks one way, then the other, scratching their head; the sign\'s arm swings round to point and off they walk (direction, way)'),
  'drum-fun': V(5, 'a kid drums on top of the kanji with two sticks; it squashes with every beat and music notes fly up (fun, music)'),
  'leaf-fall': V(3, 'a branch reaches out from the kanji, a bud unfurls into a big leaf that flutters, lets go and zigzags down to the ground (leaf)'),
  'gust-hat': V(5, 'a gust blows across: the kanji leans over, a person leans into it and their hat flies off tumbling away; the wind drops and a new hat lands (wind)'),
  'food-row': V(4, 'three plates slide in, each with a food (a rice ball, a fish, an apple); a fork stabs the fish and lifts it away (food)'),
  'fruit-bowl': V(5, 'an apple, a banana and a bunch of grapes drop one by one into a bowl and settle (fruit)'),
  'drink-straw': V(4, 'a straw drops into a glass of juice and the level goes down with rising bubbles (slurp); it refills (drink)', { color: null }),
  toaster: V(5, 'two slices of toast pop up high out of a toaster and land; an egg fries in a pan beside it (breakfast)'),
  teabag: V(4, 'a teabag dunks into a cup of hot water three times and the red-brown colour spreads; steam (black tea)'),
  'bowl-spin': V(3, 'clay spins on a potter\'s wheel and rises into a bowl, then turns glaze blue (bowl)'),
  'bento-open': V(3, 'a lunchbox lid lifts off: rice, an egg roll, a sausage; chopsticks pick something out (lunch box)'),
  ashtray: V(3, 'a cigarette is stubbed out in a dish; a curl of smoke rises and fades (ashtray)'),
  'shop-basket': V(7, 'a person with a basket walks along a shelf of goods and things hop off the shelf into the basket (shopping)'),
  'luggage-pile': V(4, 'a person staggers in under a tall pile of bags and cases, the top one teetering (luggage)'),
  'hug-treasure': V(6, 'a treasure chest opens on a glowing gem; a person hugs the chest tight, hearts rising (important, precious)'),
  'hand-wash': V(7, 'two hands rub together under a running tap, suds foaming, then shake dry (wash)'),
  laundry: V(5, 'clothes tumble round in a washing machine\'s window; it stops and shirts hop out onto a line and flap (laundry)'),
  'toilet-dash': V(5, 'a person hops from foot to foot by a door marked WC, dashes in, the door shuts; it opens and they stroll out relieved (toilet)'),
  'switch-off': V(8, 'a finger flicks a switch: the lamp goes out and it goes dark; flick, it comes back (turn off, erase)'),
  'candle-out': V(3, 'a candle flame flickers, shrinks and goes out by itself, a curl of smoke; it lights again (disappear)'),
  'gift-open': V(5, 'a wrapped present shakes, its flaps fly open and a star pops out spinning (open)'),
  'bath-tub': V(6, 'a person relaxes in a bathtub, bubbles rising, a rubber duck bobbing, steam (bath)'),
  sneeze: V(5, 'a person with a red nose: ah... ah... CHOO! a spray bursts out, a tissue flies, they shiver (a cold)'),
  'ticket-gate': V(7, 'a ticket slides out of a machine, a hand takes it, the gate\'s flaps swing open (ticket)'),
  'stamp-letter': V(5, 'a stamp flies onto the corner of an envelope with a thump, then a postmark stamps over it (postage stamp)'),
  'train-arrive': V(5, 'a train glides in along the platform and stops; a person steps off and waves (arrive)'),
  'car-park': V(4, 'a car drives in by itself and backs into a parking space, beep beep (car)'),
  'traffic-red': V(6, 'a traffic light changes green, yellow, RED; a car rolling up stops (red)'),
  neighbourhood: V(3, 'a house; little houses pop up all round it and a dotted ring draws around them (neighbourhood, nearby)'),
  'postcard-post': V(3, 'a postcard with a mountain picture flips over, lines write on its back, and it flies into a red postbox (postcard)'),
  'button-press': V(5, 'a finger presses a big red button down; it lights up and dings (push, press)'),
  keypad: V(5, 'a finger taps a number on a keypad, each key lighting up; the number appears on the screen (number)', { number: null }),
  'family-wave': V(7, 'a dad, a mum and a small kid walk out together and stand in a row waving, hearts over them (family)'),
  'animal-parade': V(9, 'a cow plods by, a bird flaps over it, a snail creeps after them (animal)'),
  'me-spotlight': V(9, 'three people; a "?" pops up; one steps forward, hand on their chest, and a spotlight lands on them (myself)'),
  'mask-off': V(5, 'a person in a funny disguise (big glasses and nose); it pops off and flies away, they smile and a green check pops up (truth, real)'),
  'classroom-kids': V(8, 'a blackboard and three desks; three kids file in and sit down at them (classroom)'),
  'talk-bubbles': V((o) => 4 + (o.words?.length ?? 3), 'two people chat; speech bubbles rise between them in different languages (language, words)', { words: null }),
  'merry-go-round': V(9, 'kids ride round and round on a merry-go-round, bobbing, notes flying (fun)'),
  'race-win': V(10, 'three runners race to a tape; the first breaks it, throws their arms up and a gold 1 pops (first, number one)'),
  'drag-suitcase': V(5, 'a person drags a huge suitcase that barely moves, leaning hard, sweat flying, then flops onto it (heavy)'),
  'spot-difference': V(3, 'two pictures side by side, almost the same; a red ring draws round the one thing that differs (differ)'),
  'confetti-shapes': V(5, 'shapes of every colour and kind pop out one after another and swirl round (various)'),
  'paint-pour': V(3, 'a can tips and paint pours over a white teddy bear, colouring it (brown; color: the paint)', { color: null }),
  'rewind-clock': V(6, 'a clock beside the kanji: its hands spin backwards, a rewind sign flashes and a little sun runs back across the sky (yesterday, previous)'),
  'ground-thud': V(6, 'the kanji hops up and slams down onto a strip of earth: cracks shoot out, grass springs up and a mole pokes its head out (ground, earth)'),
  'lid-fit': V(1, 'the top of the kanji lifts off like a lid, hovers and drops back onto the box below with a click, a sparkle (fit, join)'),
  'gate-shut': V(2, 'the two halves of the kanji (門) slide together over the middle, clunk, a padlock snaps on; then it opens again (close, shut)'),
  'kanji-wings': V(2, 'the kanji sprouts two wings, flaps, lifts off, flies up and round, then glides back down to land (fly)'),
  'scroll-write': V(4, 'a scroll unrolls beside the kanji and a brush writes a line of characters along it (writing, sentence)', { text: null }, 'text'),
  'frog-prince': V(5, 'a frog hops onto the kanji, POOF, a prince with a crown; POOF, a frog again; the kanji wobbles (change, strange)'),
  'rope-pull': V(4, 'a person with a rope tied to the kanji leans back and hauls it towards them in three heaves (pull); outcome drawer: a person pulls a drawer out of a chest (to pull)', { outcome: 'rope' }, 'outcome'),
  'stop-sign': V((o) => (o.outcome === 'car' ? 5 : 6), 'a person runs up to a stop sign (止まれ) and skids to a dead stop, arms windmilling, dust flying (stop); outcome car: a car rolls up to the sign and stops (to stop)', { outcome: 'run' }, 'outcome'),
  'refuse-spoon': V((o) => (o.outcome === 'stink' ? 6 : 5), 'a hand offers a kid a spoonful of greens; the kid turns away, arms crossed, shaking their head (dislike); outcome stink: a stinky sock dangled, the kid holds their nose (dislike)', { outcome: 'spoon' }, 'outcome'),
  'taste-spoon': V(7, 'a person dips a spoon into a steaming pot, tastes and lights up: mm! a sparkle, a belly rub (taste, flavour)'),
  'shiver-frost': V(6, 'frost creeps over the kanji and an icicle grows under it, dripping; a person beside it hugs themselves and shivers, breath puffing (cold)'),
  'sister-help': V((o) => (o.outcome === 'hair' ? 6 : 5), 'a big girl kneels and ties a little one\'s shoelace (a bow pops), then takes their hand and leads them along (older sister); outcome hair: she braids the little one\'s hair and ties a ribbon (older sister)', { outcome: 'lace' }, 'outcome'),
  'little-follow': V(4, 'a big kid walks on; a little one hurries after, bouncing; the big one waits with a hand out and they go on together (younger brother)'),
  'line-up': V((o) => (o.outcome === 'height' ? 10 : 11), 'five kids run in from both sides and line up shoulder to shoulder on a line, then all bow together (line up, row); outcome height: kids shuffle into a row from smallest to tallest (to line up)', { outcome: 'row' }, 'outcome'),
  'sing-mic': V(6, 'a person on a little stage sings into a microphone, swaying, notes pouring out, an arm flung up at the end (sing, song); outcome shower: singing in the shower (to sing)', { outcome: 'stage' }, 'outcome'),
  'egg-hatch': V((o) => (o.outcome === 'step' ? 2 : 5), 'an egg in a nest wobbles, its top pops off and a chick peeks out and blinks at the world for the first time, a sparkle (first time, beginning); outcome step: the chick climbs out and takes its first wobbly steps (for the first time)', { outcome: 'hatch' }, 'outcome'),
  'clouds-part': V((o) => (o.outcome === 'rainbow' ? 3 : 6), 'grey clouds cover the sun and rain falls; they slide apart, the sun beams out and a person throws their arms up (clear weather); outcome rainbow: the rain stops, the cloud drifts off and a rainbow arcs over (to clear up)', { outcome: 'sun' }, 'outcome'),
  'think-click': V(7, 'a person scratches their head; in the thought bubble a "?" spins and turns into "!", and up goes a finger (meaning, idea, mind)'),
  'roller-blue': V((o) => (o.outcome === 'balloon' ? 2 : 7), 'a roller paints a white wall blue stripe by stripe and a bluebird lands on top (blue; color: the paint); outcome balloon: a blue balloon blows up and floats away (blue)', { outcome: 'wall', color: null }, 'outcome'),
  'shop-open': V((o) => (o.outcome === 'veg' || o.outcome === 'closed' ? 3 : 4), 'a little shop: its shutter rolls up and the shopkeeper behind the counter waves (shop, house); outcome veg: crates of vegetables (greengrocer); closed: the shutter rolls down and a CLOSED sign swings (to be shut)', { outcome: 'open' }, 'outcome'),
  playground: V(7, 'an empty lot; a slide and a swing pop up out of the ground and kids play on them (place, venue)'),
  'build-toy': V(9, 'a toy car is put together: the body drops on, the wheels pop on, a hammer taps, and it drives off (make)'),
  'soot-puff': V(5, 'a chimney coughs a big black cloud over a person, who comes out black all over, only their eyes blinking; they shake it off (black)'),
  'stairs-down': V(5, 'a person walks down a staircase step by step; at the bottom a cloud comes and rain starts (descend, fall)'),
  'learn-fly': V(6, 'a baby bird on a branch flaps and tumbles off, tries again and tumbles; the third time it flies (learn)'),
  'subway-cut': V(5, 'the street is cut open: a train runs through a tunnel underneath while a person walks along on top (subway)'),
  'book-one': V(5, 'a book flips open to its very first page, a big 1 on it, and a start flag pops up (beginning)'),
  'weather-board': V(4, 'a weather board flips from a grey cloud to a bright smiling sun (fine weather)'),
  fridge: V(6, 'a fridge door swings open, cold mist spills out, a hand takes a bottle of milk; it shuts (refrigerator)'),
  'touch-ice': V(4, 'a fingertip touches a big ice cube and jerks back shaking, frost puffing (cold to the touch)'),
  'word-picture': V(4, 'a word card (りんご) turns over and on the back is the thing itself, an apple (meaning)', { word: null }),
  'arrange-row': V(6, 'a hand puts cups down one by one in a neat straight row (to line up, arrange)'),
  'window-shut': V(6, 'a hand slides a window shut against the wind and the curtain stops flapping (to close)'),
  'bus-off': V(4, 'a bus pulls up and a person steps down off it onto the pavement (to get off)'),
  'paper-plane': V(3, 'a hand throws a paper plane; it swoops, loops the loop and glides back round (to fly)'),
  snowman: V(5, 'snowballs roll in and stack into a snowman; a carrot nose, eyes and a scarf pop on (to make)'),
  'essay-star': V(5, 'a pencil writes a title and lines on a page; a gold star sticker slaps on (composition)'),
  'juggle-crash': V(4, 'a person juggles more and more plates, wobbling, until it all comes crashing down (terrible, very)'),
  'black-cat': V(4, 'in the dark a black cat sits, only its yellow eyes blinking, tail swishing; it walks off (black)'),
  'rain-umbrella': V(7, 'a cloud rolls over, rain begins, a person pops open an umbrella and the drops bounce off (to fall, of rain)'),
  'practice-kick': V(4, 'a person kicks a ball against a wall again and again, it bounces back each time (practice)'),
  'piano-lesson': V(10, 'a teacher plays three notes on a piano; a kid on a small keyboard copies them (to take lessons)'),
  'play-catch': V(5, 'a big brother and a little brother throw a ball back and forth (siblings)'),
  'cake-slice': V(6, '部: a round cake is cut into four and one slice slides out from the rest, then back'),
  'puzzle-fill': V(6, '全: puzzle pieces fly into a frame one by one; when it is whole it glows'),
  'body-stretch': V(2, '体: a person stretches arms up, touches the toes and twists; each body part lights up as it moves'),
  'letter-blocks': V((o) => 2 + 2 * [...(o.letters ?? 'あいう')].length, '字: letter blocks drop into a row and a little person points at each; letters: what the blocks show (漢字: 山川木)', { letters: null }, 'letters'),
  'walk-through': V(3, '通: a person walks into a tunnel through a hill and comes out the other side'),
  'cage-open': V(6, '空: a cage door opens and the bird flies out; the cage is left empty'),
  'bridge-walk': V((o) => (o.outcome === 'zebra' ? 6 : 5), '渡: a person walks over an arched bridge across a river; outcome zebra: a kid waits at a zebra crossing, the walk light turns green and they cross, hand up (渡る)', { outcome: 'bridge' }, 'outcome'),
  'paper-fold': V((o) => (o.outcome === 'letter' ? 4 : 5), '紙: a sheet of paper flutters down, folds up and hops onto a kid as a paper hat; outcome letter: a written sheet slides into an envelope, a heart seal, it flies off (手紙)', { outcome: 'hat' }, 'outcome'),
  'ice-melt': V(7, '夏: under a blazing sun an ice-cream cone in a hand melts: the scoop sags, drips fall, a puddle grows'),
  'garden-water': V(6, '庭: a watering can passes over a flower bed by a picket fence and a flower pops up under each shower'),
  'home-time': V((o) => (o.outcome === 'clock' ? 6 : 7), '夕: the sun sinks behind a hill; two kids wave goodbye and walk home while crows fly past; outcome clock: the hands sweep round to five, the chime plays and the sun sinks (夕方)', { outcome: 'wave' }, 'outcome'),
  'gift-bow': V(4, '御: a person bows deeply, offering a wrapped gift with both hands; the kanji bows back and sparkles'),
  'yellow-things': V((o) => ({ crayon: 3, hat: 6 })[o.outcome] ?? 4, '黄: a sunflower, a banana, a lemon and a rubber duck pop up one by one: all yellow; outcome crayon: a yellow crayon colours a star in (黄色); hat: a kid in yellow hat, raincoat and boots under a yellow umbrella (黄色い)', { outcome: 'things' }, 'outcome'),
  'shoe-step': V(4, '靴: a pair of shoes hops onto a mat and lines up; a barefoot kid steps in and walks off wearing them; outcome socks: striped socks instead (靴下)', { outcome: 'shoes' }, 'outcome'),
  'clouds-gather': V(5, '曇: grey clouds drift over the sun and stay; the day dims and a sunflower droops; outcome grey: cloud after cloud rolls in until the sky is grey, a kid with an umbrella looks up (曇り)', { outcome: 'sun' }, 'outcome'),
  'knock-door': V((o) => (o.outcome === 'window' ? 6 : 7), '誰: knock, knock on a door; it opens a crack and a dark figure with bright eyes peeks out under a "?"; outcome window: a dark figure walks past a lit window, stops to peek out and walks on (誰か)', { outcome: 'door' }, 'outcome'),
  'stretch-wide': V(6, '広: two hands grab the kanji by its edges and pull it out wide, an arrow showing the way; it springs back'),
  'back-to-back': V(6, '背: two kids stand back to back by a height chart; a ruler comes down on their heads and the short one goes on tiptoe'),
  'empty-box': V(6, '無: a box opens, tips forward to show its inside, turns upside down and shakes: nothing falls out; a kid shrugs'),
  'gears-click': V(7, '理: a hand slots the missing middle gear in; all three gears turn together and a lightbulb pops on'),
  'ball-steps': V((o) => (o.outcome === 'climb' ? 4 : 7), '段: a ball bounces down a numbered staircase one step at a time; each step lights up as it lands; outcome climb: a kid climbs the staircase step by step and cheers at the top (階段)', { outcome: 'ball' }, 'outcome'),
  'map-unroll': V(4, '図: a map unrolls and a dotted path draws itself from a little house to a red X'),
  'hall-rise': V((o) => ({ embassy: 9, cinema: 7 })[o.outcome] ?? 6, '館: a big columned hall rises from the ground; visitors walk up its steps and go in; outcome embassy: flags of two countries wave either side (大使館); cinema: a cinema with a film-reel sign and chasing marquee lights, people go in (映画館)', { outcome: 'hall' }, 'outcome'),
  'tool-use': V((o) => (o.outcome === 'scissors' ? 4 : 6), '使: a hand takes a wrench off a pegboard, turns a bolt with it and hangs it back on its outline; outcome scissors: scissors snip along a dotted line and the paper falls apart (使う)', { outcome: 'wrench' }, 'outcome'),
  'barbell-flex': V((o) => (o.outcome === 'car' ? 5 : 4), '強: a person lifts a barbell overhead with ease, sets it down and flexes both arms in a burst; outcome car: lifts a whole car overhead instead (強い)', { outcome: 'barbell' }, 'outcome'),
  'my-room': V(7, '部屋: a cutaway room fills up, bed, desk and lamp, rug, poster; a kid walks in and jumps for joy'),
  'sweep-all': V(4, '全部: toys scattered on the floor hop into a toy box one by one, the last one too; the lid shuts and a tick pops up'),
  dictionary: V(5, '字引: a thick book opens, its pages flip fast and a magnifying glass stops on one line, which lights up'),
  'hand-over': V(6, '渡す: one person hands a parcel across to another, who takes it and bows thanks'),
  'beach-day': V(8, '夏休み: a beach umbrella on the sand, a kid in a swim ring bobbing on the waves, a beach ball splashes down'),
  'house-heart': V(7, '家庭: the front of a little house swings open on a parent and a kid at the table inside; a heart rises'),
  'dinner-table': V((o) => (o.time === 'night' ? 11 : 8), '夕飯 / 晩御飯: dishes pop onto a table, a kid puts their hands together and eats with chopsticks; time sunset: a sinking sun in the window; night: moon and stars, a lamp and a parent too', { time: 'sunset' }, 'time'),
  'rice-cooker': V(7, '御飯: a rice cooker lid pops open in a puff of steam; a paddle scoops rice into a bowl, heaped up'),
  'fog-glass': V(6, '曇る: a kid breathes on a window, the glass fogs over; they draw a smiley in it, then it clears'),
  'room-expand': V(5, '広い: a cramped room\'s walls slide far apart; the kid inside spreads their arms and twirls'),
  'suit-up': V(6, '背広: a person in a dark suit, white collar and red tie, briefcase in hand, straightens the tie and walks off'),
  'lost-key': V(6, '無くす: a key drops out of a walking person\'s pocket; they stop, pat their pockets, "?", look back: it glints'),
  'snail-climb': V(4, '段々: a snail slowly climbs a little staircase one step at a time, leaving a trail'),
  'map-read': V(7, '地図: a person holds a map up, turns it upside down, "?", turns it back, points the way and walks off'),
  'library-shelf': V(6, '図書館: tall bookshelves full of books; one slides out and floats to a kid at a reading table, then back'),
  'study-desk': V(8, '勉強: a kid at a desk with a lamp writes line after line; a test pops up "100" with a red flower circle'),
  'car-cross': V((o) => ({ scramble: 6 })[o.outcome] ?? 5, '交: at a crossroads one car drives across and another comes up the other road: they cross; outcome scramble: zebra crossings and walk lights, two people cross corner to corner (交差点)', { outcome: 'cars' }, 'outcome'),
  'tower-gap': V(3, '差: two block towers; the right one grows taller, its extra blocks light up and a red bar measures the difference'),
  'jump-rope': V(4, '度: a kid skips rope while a counter counts the times, 1, 2, 3, 4'),
  'factory-press': V(7, '機: a ball rides a conveyor into a machine with turning gears; the press slams and a cube comes out'),
  'brick-build': V((o) => ({ tower: 2 })[o.outcome] ?? 4, '建: bricks fly in and stack into a wall; a crane lowers the roof on top; outcome tower: floor after floor drops onto a tall building and its windows light up (建物)', { outcome: 'wall' }, 'outcome'),
  'bell-ring': V(5, '音: a bell swings and rings, rings of sound ripple out; a person turns and cups an ear'),
  'errand-run': V(7, '用: a parent hands a kid a note; the kid runs off and comes back with milk; a heart'),
  'bag-carry': V((o) => ({ balloon: 5 })[o.outcome] ?? 3, '持: a hand comes down, grips a shopping bag by its handle, lifts it and swings it, then sets it down; outcome balloon: a kid holds a balloon on a string while gusts tug at it (持つ)', { outcome: 'bag' }, 'outcome'),
  'dot-point': V(4, '点: a pen taps four dots in a row; a pointer taps one and it bursts into a glowing star'),
  'turn-around': V((o) => ({ across: 6 })[o.outcome] ?? 4, '向: a person with their back to you turns round to face you, waves, then points "over there"; outcome across: someone waves to a friend on the other side of a river, who waves back (向こう)', { outcome: 'turn' }, 'outcome'),
  'stand-up': V((o) => ({ toddler: 4 })[o.outcome] ?? 4, '立: the kanji lies on its side and springs upright while a person sitting on a stool stands up; outcome toddler: a toddler pushes up, wobbles and stands with arms out, then sits back down (立つ)', { outcome: 'kanji' }, 'outcome'),
  'tape-measure': V(3, '計: a tape measure pulls out across the top of the kanji while a counter counts the centimetres'),
  'rewind-ball': V(3, '再: a ball rolls off a table and bounces; it all rewinds and plays again'),
  'shop-counter': V((o) => ({ cafe: 7 })[o.outcome] ?? 9, '店: a stall with a striped awning; a customer pays a coin, the till dings, the shopkeeper hands over a bag; outcome cafe: at a café table a waiter brings a steaming coffee and cake on a tray (喫茶店)', { outcome: 'stall' }, 'outcome'),
  'phone-charge': V((o) => ({ water: 7 })[o.outcome] ?? 7, '要: a phone battery blinks red with a "!"; a hand plugs the charger in and it fills up green; outcome water: a person wilting in the sun spots a water bottle, drinks and perks up (要る)', { outcome: 'phone' }, 'outcome'),
  'wardrobe-dress': V(7, '服: a wardrobe opens, a red shirt and blue trousers fly out onto a person, who twirls in them'),
  'easel-paint': V(6, '画: on an easel a brush paints a hill and a sun; a gold frame drops round the picture'),
  'projector': V((o) => ({ popcorn: 8 })[o.outcome] ?? 6, '映: a projector beam lights a screen behind the kanji, where a little figure runs across; outcome popcorn: an audience in red seats watches a flickering screen, popcorn pops (映画)', { outcome: 'beam' }, 'outcome'),
  'pot-cook': V((o) => ({ pan: 7 })[o.outcome] ?? 7, '料: a carrot, a fish and a rice ball drop into a pot on the stove; a ladle stirs and steam rises; outcome pan: a chef in a tall hat tosses an omelette in a frying pan (料理)', { outcome: 'pot' }, 'outcome'),
  'bus-ride': V((o) => ({ bike: 5 })[o.outcome] ?? 5, '乗: a bus pulls up, a person gets on and waves from the window as it drives off; outcome bike: a kid gets on a bicycle and pedals away (乗る)', { outcome: 'bus' }, 'outcome'),
  'fever': V((o) => ({ touch: 6 })[o.outcome] ?? 6, '熱: a thermometer in a mouth shoots up red, the face goes red, steam puffs from the ears; an ice pack cools them down; outcome touch: a hand touches a steaming kettle and jerks back with a red flash (熱い)', { outcome: 'fever' }, 'outcome'),
  'brush-enso': V((o) => ({ pencil: 4, pen: 4 })[o.outcome] ?? 5, '筆: a big writing brush dips into an ink stone and paints a circle in one sweep, flicking ink; outcome pencil: a pencil writes, then is sharpened, shavings curl (鉛筆); pen: a fountain pen dips in ink and signs (万年筆)', { outcome: 'brush' }, 'outcome'),
  'cow-moo': V((o) => ({ milk: 7, steak: 8 })[o.outcome] ?? 7, '牛: a cow walks in, says モー in rings of sound, and a milk pail fills up; outcome milk: a carton pours milk into a glass, a kid drinks and gets a moustache (牛乳); steak: a steak sizzles and flips on a grill, a little cow sign in it (牛肉)', { outcome: 'cow' }, 'outcome'),
  'heart-beat': V(4, '心: a heart glows in a chest, beating lub-dub; the person hugs themselves and it beats bigger'),
  'parent-watch': V(5, '親: a parent walks with a small kid; the kid runs ahead and the parent climbs a stump to watch over them'),
  'police-box': V(9, '交番: a little police box with a red lamp; the officer bends down and points a lost kid the way'),
  'parasol-up': V(7, '差す: a person sweating under a blazing sun holds a parasol up over their head; it pops open and shade falls'),
  'stopwatch-exact': V(7, '丁度: a stopwatch counts up and a thumb stops it on exactly 10.00; a tick and a sparkle'),
  'plane-takeoff': V(3, '飛行機: a plane speeds down a runway, lifts off and climbs away trailing a contrail'),
  'headphones-dance': V(4, '音楽: a kid with big headphones bobs and dances while colourful notes float out'),
  'cuckoo-clock': V(7, '時計: a cuckoo clock: the hands sweep round to twelve, the door opens and the bird pops out twice'),
  'year-hop': V(7, '再来年: three calendar blocks (now, +1, +2); a kid hops two ahead and cheers'),
  'flower-gasp': V(6, '美: a bud opens into a big pink flower, sparkles circle it; a person gasps, hands on their cheeks'),
  'podium-win': V(8, '最: three runners race up to a podium; the winner stands on the top step and lifts a gold trophy'),
  'face-change': V(6, '面: a big round face smiles, goes wide-eyed with an O mouth, then winks'),
  'apple-sell': V(10, '売: a seller behind a crate of apples holds one up; a buyer pays a coin and gets the apple'),
  'race-start': V(7, '始: two runners crouch at the start line; the flag drops and they dash off in a puff of dust'),
  'curtain-close': V(7, '終: on a little stage an actor bows; the red curtains slide shut and おわり appears on them'),
  'move-in': V(6, '住: a person carries a box into a little house; its window lights up and the chimney puffs smoke'),
  'banana-trip': V(4, '転: a person steps on a banana peel, flips head over heels and lands sitting, stars circling their head'),
  'sick-bed': V(9, '病: a pale person in bed with a red nose and an ice bag sneezes; pills on the nightstand'),
  'ambulance': V(5, '院: an ambulance with a flashing light pulls up at a building with a red cross; its doors slide open'),
  'walk-far': V(3, '遠: a person waves goodbye and walks away down a long road towards far mountains, smaller and smaller'),
  'mirror-dance': V(5, '同: two people side by side do exactly the same jumping jacks; an equals sign glows above'),
  'wedding': V(10, '夫: a groom in a suit and a bride in white; rings float to them, confetti falls and a heart rises'),
  'post-kick': V(5, '丈: a kid kicks a thick wooden post that does not budge, then hops holding a sore foot'),
  'alarm-wake': V(9, '起: an alarm clock rings and hops; the person asleep in bed sits bolt upright, hair sticking up, and stretches'),
  'home-greet': V(8, '帰: a person walks up to a house at dusk; the door opens, warm light spills out and the family comes out for a hug'),
  'toast-run': V(7, '遅: a kid runs with toast in their mouth, sweat flying, under a clock whose hands spin'),
  'mud-splash': V(4, '汚: a person in white steps in a puddle; mud splashes up and their clothes go brown'),
  'hand-question': V(7, '問: a kid raises a hand under a big "?" speech bubble; the grown-up beside scratches their head'),
  'title-stamp': V(4, '題: a red title band slams onto a notebook, is underlined, and text lines fill in below'),
  'inn-sleep': V(10, '宿: a traveller with a suitcase walks into a little inn; the window lights, goes dark and Zzz floats up'),
  'grab-apple': V(4, '取: a hand reaches in, grabs the apple off a table and pulls it away, leaving the table empty'),
  'gem-test': V(8, '真: a magnifying glass passes over two gems: the real one sparkles (tick), the fake cracks (cross)'),
  'photo-snap': V(10, '写: a person poses with a peace sign; the camera flashes and a photo slides out and develops'),
  'ocean-ship': V(4, '洋: waves roll across a wide sea; a ship sails along the horizon, puffing smoke'),
  kit: V(21, 'review sheet of the props kit: hand poses, a person walking, hammer, nail, board, plate, ball, heart, burst (not for cards)', { pose: 'all' }),
};
