// The "vignette" slot's catalog: every scene type, its options (with defaults) and the draw calls it builds. Pure data, no
// three.js (Node scripts import it through catalog.js). Implementations: src/effects/vignettes/ (one module per theme).
// Every vignette also takes `at` ([x, y] offset of its actors in glyph heights) and `size` (scale of its actors, about the
// kanji's bottom-right corner: scenes that act on the kanji itself should keep it 1).
// A vignette uses no particle slots and no lights of its own; draw calls must equal what it builds (npm run e2e checks).
//   variant: the option that tells two uses of one type apart (上手 / 下手: one set-up, two outcomes)
// the row of time tiles in step1-time.js: the cards, plus one mesh for suns, two for clocks, or a label per tile
const rowDc = (unit) => 1 + (({ day: 1, now: 2 })[unit] ?? 3);
const V = (dc, desc, opts = {}, variant = null) => ({ dc, desc, opts: { at: null, size: null, ...opts }, variant });

export const VIGNETTES = {
  'hammer-nail': V(10, 'a hand swings a hammer at a nail standing in a board; outcome clean: three blows drive it in flush, a sparkle, thumbs up (skilled); bend: the nail bends over, the hammer hits the thumb, stars (unskilled)', { outcome: 'clean' }, 'outcome'),
  push: V(3, 'a person walks up beside the kanji, leans in and shoves it along in three heaves, dust puffing where it scrapes (push); dir: the way it is pushed (left: they stand on its right)', { dir: 'left' }),
  'lift-heavy': V(4, 'a person squats, grips the kanji and strains (shaking, sweat flying); it barely lifts and thuds down, knocking them onto their bottom (heavy)'),
  'come-near': V((o) => (o.outcome === 'face' ? 2 : 3), 'a person far down a path walks towards you, growing, until they stand right beside the kanji and lean in close (near); outcome face: they step and lean towards you until their face is right up close (close)', { outcome: 'walk' }, 'outcome'),
  'stack-plates': V((o) => (o.outcome === 'dry' ? 7 : 2), 'the kanji is the stand: plates fly in and stack on it with a clink, the top one wobbles, a cake lands on it (dish, plate); outcome dry: a hand wipes a wet plate until it gleams and sets it on the pile', { outcome: 'stack' }, 'outcome'),
  'odd-one-out': V(4, 'a row of identical blue balls bounces along in step; one is red and square and hops out of time; a magnifier finds it, a cross pops up (different, wrong)'),
  'hand-in-hand': V(5, 'two people walk in from either side, meet in front of the kanji, take hands and swing them, hearts rising (two people, a couple)'),
  'box-tumble': V(9, 'a box beside the kanji pops its flaps; things tumble out one after another (ball, cup, apple, shoe) into a heap, the last one bonking the kanji; they hop back in (thing, things)'),
  'house-build': V(7, 'a wall rises behind the kanji, a roof drops on, the chimney smokes; a person walks home, goes in the door and the window lights up (house, home)'),
  'scrub-wash': V(8, 'mud splats onto the kanji; a hand scrubs it with a sponge, foam builds, a bucket tips water over it and it sparkles (wash)'),
  'tea-pour': V(6, 'tea leaves drop into a teapot, it rattles, tips and pours a green stream into a cup that fills and steams (tea); outcome serve: the cup slides forward to you on its saucer with a bow (tea, served)', { outcome: 'pour' }, 'outcome'),
  'rice-bowl': V(6, 'rice plops into a bowl in heaps and steams; chopsticks dip in and lift clumps away until it is empty (meal, rice)'),
  'sunset-lights': V(6, 'the sun sinks behind a hill with little houses, dusk falls, their windows light up one by one, the moon rises, stars come out (nightfall, evening)'),
  'calendar-back': V((o) => 3 + (o.days ?? 1), 'a calendar shows today; its page flips back a day (days 2: two) while a little sun runs backwards across the sky (yesterday)', { days: 1 }, 'days'),
  'go-to-bed': V(10, 'a person yawns, lies down on a futon and pulls up the blanket; dusk falls, the moon rises, stars twinkle, Zzz floats up (night)'),
  'noon-sun': V((o) => (o.outcome === 'eat' ? 4 : 7), 'the sun climbs from the horizon to straight overhead, the person looking up after it; at the top it flares, they cheer and open their lunchbox (noon, daytime); outcome eat: they sit and eat a rice ball under it (lunch)', { outcome: 'rise' }, 'outcome'),
  'chop-split': V((o) => (o.food ? 4 : 2), 'a cleaver chops straight down through the middle of the kanji; a flash along the cut and the halves slide apart, then back (cut); food carrot: a carrot on a board chopped into rounds (to cut)', { food: null }, 'food'),
  'todo-list': V(4, 'a pencil ticks the three boxes of a to-do list one by one; the list spins round and starts again (matter, things to do)'),
  'pin-drop': V(5, 'a big map pin drops from the sky and stabs into the ground beside the kanji, a ring pulsing out; a person runs over and waves from the spot (place)'),
  'dart-bullseye': V(5, 'darts fly from where you stand into the bullseye of a target one by one; it wobbles, a ding (hit, correct)'),
  'apple-ripen': V(4, 'a green apple on a branch ripens yellow then red, swells, sparkles and drops; a new one grows (red)'),
  'eraser-rub': V(4, 'a hand rubs the strokes out one by one with an eraser, crumbs falling; then they write back in (erase)'),
  'wheels-roll': V(4, 'wheels pop out under the kanji, it revs with puffs of exhaust and drives off to the right, then back (move)'),
  'coat-on': V((o) => (o.outcome === 'jacket' ? 5 : 4), 'a person walks in and stops on a mat beside the kanji (arrive); a coat drops onto them, the sleeves slide down, they tug it straight and twirl (wear); outcome wear: the buttons done up one by one (to wear); jacket: lifted off a stand and swung on (jacket)', { outcome: 'arrive', color: null }, 'outcome'),
  'mirror-me': V(6, 'a person in front of a standing mirror; their face looks back from the glass; they point at their own nose (the Japanese "me"), the reflection too, a sparkle (oneself)'),
  'big-brother': V((o) => (o.outcome === 'piggyback' ? 4 : 5), 'a big kid holds a ball up high while a small one hops for it; he laughs, hands it down and pats the small one\'s head (older brother); outcome piggyback: carries the small one on his back', { outcome: 'ball' }, 'outcome'),
  'teach-board': V(9, 'a teacher writes 1+1=2 on a blackboard, tapping with a pointer; a small pupil shoots a hand up and a lightbulb pops on (teach); text: what is written', { text: null }, 'text'),
  'queue-number': V(8, 'three people queue at a counter under a number sign; it counts 1, 2, 3 and each time the front one is served and walks off, the rest shuffle up (turn, number)'),
  'which-way': V(4, 'a person by a signpost looks one way, then the other, scratching their head; the sign\'s arm swings round to point and off they walk (direction, way)'),
  'drum-fun': V(5, 'a kid drums on top of the kanji with two sticks; it squashes with every beat and music notes fly up (fun, music)'),
  'leaf-fall': V(3, 'a branch reaches out from the kanji, a bud unfurls into a big leaf that flutters, lets go and zigzags down to the ground (leaf)'),
  'gust-hat': V(5, 'a gust blows across: the kanji leans over, a person leans into it and their hat flies off tumbling away; the wind drops and a new hat lands (wind)'),
  'food-row': V(4, 'three plates slide in, each with a food (a rice ball, a fish, an apple); a fork stabs the fish and lifts it away (food)'),
  'fruit-bowl': V(5, 'an apple, a banana and a bunch of grapes drop one by one into a bowl and settle (fruit)'),
  'drink-straw': V(4, 'a straw drops into a glass of juice and the level goes down with rising bubbles (slurp); it refills (drink)', { color: null }),
  toaster: V(5, 'two slices of toast pop up high out of a toaster and land; an egg fries in a pan beside it (breakfast)'),
  teabag: V(4, 'a teabag dunks into a cup of hot water three times and the red-brown colour spreads; steam (black tea)'),
  'bowl-spin': V(3, 'clay spins on a potter\'s wheel and rises into a bowl, then turns glaze blue (bowl)'),
  'bento-open': V(3, 'a lunchbox lid lifts off: rice, an egg roll, a sausage; chopsticks pick something out (lunch box)'),
  ashtray: V(3, 'a cigarette is stubbed out in a dish; a curl of smoke rises and fades (ashtray)'),
  'shop-basket': V(7, 'a person with a basket walks along a shelf of goods and things hop off the shelf into the basket (shopping)'),
  'luggage-pile': V(4, 'a person staggers in under a tall pile of bags and cases, the top one teetering (luggage)'),
  'hug-treasure': V(6, 'a treasure chest opens on a glowing gem; a person hugs the chest tight, hearts rising (important, precious)'),
  'hand-wash': V(7, 'two hands rub together under a running tap, suds foaming, then shake dry (wash)'),
  laundry: V(5, 'clothes tumble round in a washing machine\'s window; it stops and shirts hop out onto a line and flap (laundry)'),
  'toilet-dash': V(5, 'a person hops from foot to foot by a door marked WC, dashes in, the door shuts; it opens and they stroll out relieved (toilet)'),
  'switch-off': V(8, 'a finger flicks a switch: the lamp goes out and it goes dark; flick, it comes back (turn off, erase)'),
  'candle-out': V(3, 'a candle flame flickers, shrinks and goes out by itself, a curl of smoke; it lights again (disappear)'),
  'gift-open': V(5, 'a wrapped present shakes, its flaps fly open and a star pops out spinning (open)'),
  'bath-tub': V(6, 'a person relaxes in a bathtub, bubbles rising, a rubber duck bobbing, steam (bath)'),
  sneeze: V(5, 'a person with a red nose: ah... ah... CHOO! a spray bursts out, a tissue flies, they shiver (a cold)'),
  'ticket-gate': V(7, 'a ticket slides out of a machine, a hand takes it, the gate\'s flaps swing open (ticket)'),
  'stamp-letter': V(5, 'a stamp flies onto the corner of an envelope with a thump, then a postmark stamps over it (postage stamp)'),
  'train-arrive': V(5, 'a train glides in along the platform and stops; a person steps off and waves (arrive)'),
  'car-park': V(4, 'a car drives in by itself and backs into a parking space, beep beep (car)'),
  'traffic-red': V(6, 'a traffic light changes green, yellow, RED; a car rolling up stops (red)'),
  neighbourhood: V(3, 'a house; little houses pop up all round it and a dotted ring draws around them (neighbourhood, nearby)'),
  'postcard-post': V(3, 'a postcard with a mountain picture flips over, lines write on its back, and it flies into a red postbox (postcard)'),
  'button-press': V(5, 'a finger presses a big red button down; it lights up and dings (push, press)'),
  keypad: V(5, 'a finger taps a number on a keypad, each key lighting up; the number appears on the screen (number)', { number: null }),
  'family-wave': V(7, 'a dad, a mum and a small kid walk out together and stand in a row waving, hearts over them (family)'),
  'animal-parade': V(9, 'a cow plods by, a bird flaps over it, a snail creeps after them (animal)'),
  'me-spotlight': V(9, 'three people; a "?" pops up; one steps forward, hand on their chest, and a spotlight lands on them (myself)'),
  'mask-off': V(5, 'a person in a funny disguise (big glasses and nose); it pops off and flies away, they smile and a green check pops up (truth, real)'),
  'classroom-kids': V(8, 'a blackboard and three desks; three kids file in and sit down at them (classroom)'),
  'talk-bubbles': V((o) => 4 + (o.words?.length ?? 3), 'two people chat; speech bubbles rise between them in different languages (language, words)', { words: null }),
  'merry-go-round': V(9, 'kids ride round and round on a merry-go-round, bobbing, notes flying (fun)'),
  'race-win': V(10, 'three runners race to a tape; the first breaks it, throws their arms up and a gold 1 pops (first, number one)'),
  'drag-suitcase': V(5, 'a person drags a huge suitcase that barely moves, leaning hard, sweat flying, then flops onto it (heavy)'),
  'spot-difference': V(3, 'two pictures side by side, almost the same; a red ring draws round the one thing that differs (differ)'),
  'confetti-shapes': V(5, 'shapes of every colour and kind pop out one after another and swirl round (various)'),
  'paint-pour': V(3, 'a can tips and paint pours over a white teddy bear, colouring it (brown; color: the paint)', { color: null }),
  'rewind-clock': V(6, 'a clock beside the kanji: its hands spin backwards, a rewind sign flashes and a little sun runs back across the sky (yesterday, previous)'),
  'ground-thud': V(6, 'the kanji hops up and slams down onto a strip of earth: cracks shoot out, grass springs up and a mole pokes its head out (ground, earth)'),
  'lid-fit': V(1, 'the top of the kanji lifts off like a lid, hovers and drops back onto the box below with a click, a sparkle (fit, join)'),
  'gate-shut': V(2, 'the two halves of the kanji (門) slide together over the middle, clunk, a padlock snaps on; then it opens again (close, shut)'),
  'kanji-wings': V(2, 'the kanji sprouts two wings, flaps, lifts off, flies up and round, then glides back down to land (fly)'),
  'scroll-write': V(4, 'a scroll unrolls beside the kanji and a brush writes a line of characters along it (writing, sentence)', { text: null }, 'text'),
  'frog-prince': V(5, 'a frog hops onto the kanji, POOF, a prince with a crown; POOF, a frog again; the kanji wobbles (change, strange)'),
  'rope-pull': V(4, 'a person with a rope tied to the kanji leans back and hauls it towards them in three heaves (pull); outcome drawer: a person pulls a drawer out of a chest (to pull)', { outcome: 'rope' }, 'outcome'),
  'stop-sign': V((o) => (o.outcome === 'car' ? 5 : 6), 'a person runs up to a stop sign (止まれ) and skids to a dead stop, arms windmilling, dust flying (stop); outcome car: a car rolls up to the sign and stops (to stop)', { outcome: 'run' }, 'outcome'),
  'refuse-spoon': V((o) => (o.outcome === 'stink' ? 6 : 5), 'a hand offers a kid a spoonful of greens; the kid turns away, arms crossed, shaking their head (dislike); outcome stink: a stinky sock dangled, the kid holds their nose (dislike)', { outcome: 'spoon' }, 'outcome'),
  'taste-spoon': V(7, 'a person dips a spoon into a steaming pot, tastes and lights up: mm! a sparkle, a belly rub (taste, flavour)'),
  'shiver-frost': V(6, 'frost creeps over the kanji and an icicle grows under it, dripping; a person beside it hugs themselves and shivers, breath puffing (cold)'),
  'sister-help': V((o) => (o.outcome === 'hair' ? 6 : 5), 'a big girl kneels and ties a little one\'s shoelace (a bow pops), then takes their hand and leads them along (older sister); outcome hair: she braids the little one\'s hair and ties a ribbon (older sister)', { outcome: 'lace' }, 'outcome'),
  'little-follow': V(4, 'a big kid walks on; a little one hurries after, bouncing; the big one waits with a hand out and they go on together (younger brother)'),
  'line-up': V((o) => (o.outcome === 'height' ? 10 : 11), 'five kids run in from both sides and line up shoulder to shoulder on a line, then all bow together (line up, row); outcome height: kids shuffle into a row from smallest to tallest (to line up)', { outcome: 'row' }, 'outcome'),
  'sing-mic': V(6, 'a person on a little stage sings into a microphone, swaying, notes pouring out, an arm flung up at the end (sing, song); outcome shower: singing in the shower (to sing)', { outcome: 'stage' }, 'outcome'),
  'egg-hatch': V((o) => (o.outcome === 'step' ? 2 : 5), 'an egg in a nest wobbles, its top pops off and a chick peeks out and blinks at the world for the first time, a sparkle (first time, beginning); outcome step: the chick climbs out and takes its first wobbly steps (for the first time)', { outcome: 'hatch' }, 'outcome'),
  'clouds-part': V((o) => (o.outcome === 'rainbow' ? 3 : 6), 'grey clouds cover the sun and rain falls; they slide apart, the sun beams out and a person throws their arms up (clear weather); outcome rainbow: the rain stops, the cloud drifts off and a rainbow arcs over (to clear up)', { outcome: 'sun' }, 'outcome'),
  'think-click': V(7, 'a person scratches their head; in the thought bubble a "?" spins and turns into "!", and up goes a finger (meaning, idea, mind)'),
  'roller-blue': V((o) => (o.outcome === 'balloon' ? 2 : 7), 'a roller paints a white wall blue stripe by stripe and a bluebird lands on top (blue; color: the paint); outcome balloon: a blue balloon blows up and floats away (blue)', { outcome: 'wall', color: null }, 'outcome'),
  'shop-open': V((o) => (o.outcome === 'veg' || o.outcome === 'closed' ? 3 : 4), 'a little shop: its shutter rolls up and the shopkeeper behind the counter waves (shop, house); outcome veg: crates of vegetables (greengrocer); closed: the shutter rolls down and a CLOSED sign swings (to be shut)', { outcome: 'open' }, 'outcome'),
  playground: V(7, 'an empty lot; a slide and a swing pop up out of the ground and kids play on them (place, venue)'),
  'build-toy': V(9, 'a toy car is put together: the body drops on, the wheels pop on, a hammer taps, and it drives off (make)'),
  'soot-puff': V(5, 'a chimney coughs a big black cloud over a person, who comes out black all over, only their eyes blinking; they shake it off (black)'),
  'stairs-down': V(5, 'a person walks down a staircase step by step; at the bottom a cloud comes and rain starts (descend, fall)'),
  'learn-fly': V(6, 'a baby bird on a branch flaps and tumbles off, tries again and tumbles; the third time it flies (learn)'),
  'subway-cut': V(5, 'the street is cut open: a train runs through a tunnel underneath while a person walks along on top (subway)'),
  'book-one': V(5, 'a book flips open to its very first page, a big 1 on it, and a start flag pops up (beginning)'),
  'weather-board': V(4, 'a weather board flips from a grey cloud to a bright smiling sun (fine weather)'),
  fridge: V(6, 'a fridge door swings open, cold mist spills out, a hand takes a bottle of milk; it shuts (refrigerator)'),
  'touch-ice': V(4, 'a fingertip touches a big ice cube and jerks back shaking, frost puffing (cold to the touch)'),
  'word-picture': V(4, 'a word card (りんご) turns over and on the back is the thing itself, an apple (meaning)', { word: null }),
  'arrange-row': V(6, 'a hand puts cups down one by one in a neat straight row (to line up, arrange)'),
  'window-shut': V(6, 'a hand slides a window shut against the wind and the curtain stops flapping (to close)'),
  'bus-off': V(4, 'a bus pulls up and a person steps down off it onto the pavement (to get off)'),
  'paper-plane': V(3, 'a hand throws a paper plane; it swoops, loops the loop and glides back round (to fly)'),
  snowman: V(5, 'snowballs roll in and stack into a snowman; a carrot nose, eyes and a scarf pop on (to make)'),
  'essay-star': V(5, 'a pencil writes a title and lines on a page; a gold star sticker slaps on (composition)'),
  'juggle-crash': V(4, 'a person juggles more and more plates, wobbling, until it all comes crashing down (terrible, very)'),
  'black-cat': V(4, 'in the dark a black cat sits, only its yellow eyes blinking, tail swishing; it walks off (black)'),
  'rain-umbrella': V(7, 'a cloud rolls over, rain begins, a person pops open an umbrella and the drops bounce off (to fall, of rain)'),
  'practice-kick': V(4, 'a person kicks a ball against a wall again and again, it bounces back each time (practice)'),
  'piano-lesson': V(10, 'a teacher plays three notes on a piano; a kid on a small keyboard copies them (to take lessons)'),
  'play-catch': V(5, 'a big brother and a little brother throw a ball back and forth (siblings)'),
  'cake-slice': V(6, '部: a round cake is cut into four and one slice slides out from the rest, then back'),
  'puzzle-fill': V(6, '全: puzzle pieces fly into a frame one by one; when it is whole it glows'),
  'body-stretch': V(2, '体: a person stretches arms up, touches the toes and twists; each body part lights up as it moves'),
  'letter-blocks': V((o) => 2 + 2 * [...(o.letters ?? 'あいう')].length, '字: letter blocks drop into a row and a little person points at each; letters: what the blocks show (漢字: 山川木)', { letters: null }, 'letters'),
  'walk-through': V(3, '通: a person walks into a tunnel through a hill and comes out the other side'),
  'cage-open': V(6, '空: a cage door opens and the bird flies out; the cage is left empty'),
  'bridge-walk': V((o) => (o.outcome === 'zebra' ? 6 : 5), '渡: a person walks over an arched bridge across a river; outcome zebra: a kid waits at a zebra crossing, the walk light turns green and they cross, hand up (渡る)', { outcome: 'bridge' }, 'outcome'),
  'paper-fold': V((o) => (o.outcome === 'letter' ? 4 : 5), '紙: a sheet of paper flutters down, folds up and hops onto a kid as a paper hat; outcome letter: a written sheet slides into an envelope, a heart seal, it flies off (手紙)', { outcome: 'hat' }, 'outcome'),
  'ice-melt': V(7, '夏: under a blazing sun an ice-cream cone in a hand melts: the scoop sags, drips fall, a puddle grows'),
  'garden-water': V(6, '庭: a watering can passes over a flower bed by a picket fence and a flower pops up under each shower'),
  'home-time': V((o) => (o.outcome === 'clock' ? 6 : 7), '夕: the sun sinks behind a hill; two kids wave goodbye and walk home while crows fly past; outcome clock: the hands sweep round to five, the chime plays and the sun sinks (夕方)', { outcome: 'wave' }, 'outcome'),
  'gift-bow': V(4, '御: a person bows deeply, offering a wrapped gift with both hands; the kanji bows back and sparkles'),
  'yellow-things': V((o) => ({ crayon: 3, hat: 6 })[o.outcome] ?? 4, '黄: a sunflower, a banana, a lemon and a rubber duck pop up one by one: all yellow; outcome crayon: a yellow crayon colours a star in (黄色); hat: a kid in yellow hat, raincoat and boots under a yellow umbrella (黄色い)', { outcome: 'things' }, 'outcome'),
  'shoe-step': V(4, '靴: a pair of shoes hops onto a mat and lines up; a barefoot kid steps in and walks off wearing them; outcome socks: striped socks instead (靴下)', { outcome: 'shoes' }, 'outcome'),
  'clouds-gather': V(5, '曇: grey clouds drift over the sun and stay; the day dims and a sunflower droops; outcome grey: cloud after cloud rolls in until the sky is grey, a kid with an umbrella looks up (曇り)', { outcome: 'sun' }, 'outcome'),
  'knock-door': V((o) => (o.outcome === 'window' ? 6 : 7), '誰: knock, knock on a door; it opens a crack and a dark figure with bright eyes peeks out under a "?"; outcome window: a dark figure walks past a lit window, stops to peek out and walks on (誰か)', { outcome: 'door' }, 'outcome'),
  'stretch-wide': V(6, '広: two hands grab the kanji by its edges and pull it out wide, an arrow showing the way; it springs back'),
  'back-to-back': V(6, '背: two kids stand back to back by a height chart; a ruler comes down on their heads and the short one goes on tiptoe'),
  'empty-box': V(6, '無: a box opens, tips forward to show its inside, turns upside down and shakes: nothing falls out; a kid shrugs'),
  'gears-click': V(7, '理: a hand slots the missing middle gear in; all three gears turn together and a lightbulb pops on'),
  'ball-steps': V((o) => (o.outcome === 'climb' ? 4 : 7), '段: a ball bounces down a numbered staircase one step at a time; each step lights up as it lands; outcome climb: a kid climbs the staircase step by step and cheers at the top (階段)', { outcome: 'ball' }, 'outcome'),
  'map-unroll': V(4, '図: a map unrolls and a dotted path draws itself from a little house to a red X'),
  'hall-rise': V((o) => ({ embassy: 9, cinema: 7 })[o.outcome] ?? 6, '館: a big columned hall rises from the ground; visitors walk up its steps and go in; outcome embassy: flags of two countries wave either side (大使館); cinema: a cinema with a film-reel sign and chasing marquee lights, people go in (映画館)', { outcome: 'hall' }, 'outcome'),
  'tool-use': V((o) => (o.outcome === 'scissors' ? 4 : 6), '使: a hand takes a wrench off a pegboard, turns a bolt with it and hangs it back on its outline; outcome scissors: scissors snip along a dotted line and the paper falls apart (使う)', { outcome: 'wrench' }, 'outcome'),
  'barbell-flex': V((o) => (o.outcome === 'car' ? 5 : 4), '強: a person lifts a barbell overhead with ease, sets it down and flexes both arms in a burst; outcome car: lifts a whole car overhead instead (強い)', { outcome: 'barbell' }, 'outcome'),
  'my-room': V(7, '部屋: a cutaway room fills up, bed, desk and lamp, rug, poster; a kid walks in and jumps for joy'),
  'sweep-all': V(4, '全部: toys scattered on the floor hop into a toy box one by one, the last one too; the lid shuts and a tick pops up'),
  dictionary: V(5, '字引: a thick book opens, its pages flip fast and a magnifying glass stops on one line, which lights up'),
  'hand-over': V(6, '渡す: one person hands a parcel across to another, who takes it and bows thanks'),
  'beach-day': V(8, '夏休み: a beach umbrella on the sand, a kid in a swim ring bobbing on the waves, a beach ball splashes down'),
  'house-heart': V(7, '家庭: the front of a little house swings open on a parent and a kid at the table inside; a heart rises'),
  'dinner-table': V((o) => (o.time === 'night' ? 11 : 8), '夕飯 / 晩御飯: dishes pop onto a table, a kid puts their hands together and eats with chopsticks; time sunset: a sinking sun in the window; night: moon and stars, a lamp and a parent too', { time: 'sunset' }, 'time'),
  'rice-cooker': V(7, '御飯: a rice cooker lid pops open in a puff of steam; a paddle scoops rice into a bowl, heaped up'),
  'fog-glass': V(6, '曇る: a kid breathes on a window, the glass fogs over; they draw a smiley in it, then it clears'),
  'room-expand': V(5, '広い: a cramped room\'s walls slide far apart; the kid inside spreads their arms and twirls'),
  'suit-up': V(6, '背広: a person in a dark suit, white collar and red tie, briefcase in hand, straightens the tie and walks off'),
  'lost-key': V(6, '無くす: a key drops out of a walking person\'s pocket; they stop, pat their pockets, "?", look back: it glints'),
  'snail-climb': V(4, '段々: a snail slowly climbs a little staircase one step at a time, leaving a trail'),
  'map-read': V(7, '地図: a person holds a map up, turns it upside down, "?", turns it back, points the way and walks off'),
  'library-shelf': V(6, '図書館: tall bookshelves full of books; one slides out and floats to a kid at a reading table, then back'),
  'study-desk': V(8, '勉強: a kid at a desk with a lamp writes line after line; a test pops up "100" with a red flower circle'),
  'car-cross': V((o) => ({ scramble: 6 })[o.outcome] ?? 5, '交: at a crossroads one car drives across and another comes up the other road: they cross; outcome scramble: zebra crossings and walk lights, two people cross corner to corner (交差点)', { outcome: 'cars' }, 'outcome'),
  'tower-gap': V(3, '差: two block towers; the right one grows taller, its extra blocks light up and a red bar measures the difference'),
  'jump-rope': V(4, '度: a kid skips rope while a counter counts the times, 1, 2, 3, 4'),
  'factory-press': V(7, '機: a ball rides a conveyor into a machine with turning gears; the press slams and a cube comes out'),
  'brick-build': V((o) => ({ tower: 2 })[o.outcome] ?? 4, '建: bricks fly in and stack into a wall; a crane lowers the roof on top; outcome tower: floor after floor drops onto a tall building and its windows light up (建物)', { outcome: 'wall' }, 'outcome'),
  'bell-ring': V(5, '音: a bell swings and rings, rings of sound ripple out; a person turns and cups an ear'),
  'errand-run': V(7, '用: a parent hands a kid a note; the kid runs off and comes back with milk; a heart'),
  'bag-carry': V((o) => ({ balloon: 5 })[o.outcome] ?? 3, '持: a hand comes down, grips a shopping bag by its handle, lifts it and swings it, then sets it down; outcome balloon: a kid holds a balloon on a string while gusts tug at it (持つ)', { outcome: 'bag' }, 'outcome'),
  'dot-point': V(4, '点: a pen taps four dots in a row; a pointer taps one and it bursts into a glowing star'),
  'turn-around': V((o) => ({ across: 6 })[o.outcome] ?? 4, '向: a person with their back to you turns round to face you, waves, then points "over there"; outcome across: someone waves to a friend on the other side of a river, who waves back (向こう)', { outcome: 'turn' }, 'outcome'),
  'stand-up': V((o) => ({ toddler: 4 })[o.outcome] ?? 4, '立: the kanji lies on its side and springs upright while a person sitting on a stool stands up; outcome toddler: a toddler pushes up, wobbles and stands with arms out, then sits back down (立つ)', { outcome: 'kanji' }, 'outcome'),
  'tape-measure': V(3, '計: a tape measure pulls out across the top of the kanji while a counter counts the centimetres'),
  'rewind-ball': V(3, '再: a ball rolls off a table and bounces; it all rewinds and plays again'),
  'shop-counter': V((o) => ({ cafe: 7 })[o.outcome] ?? 9, '店: a stall with a striped awning; a customer pays a coin, the till dings, the shopkeeper hands over a bag; outcome cafe: at a café table a waiter brings a steaming coffee and cake on a tray (喫茶店)', { outcome: 'stall' }, 'outcome'),
  'phone-charge': V((o) => ({ water: 7 })[o.outcome] ?? 7, '要: a phone battery blinks red with a "!"; a hand plugs the charger in and it fills up green; outcome water: a person wilting in the sun spots a water bottle, drinks and perks up (要る)', { outcome: 'phone' }, 'outcome'),
  'wardrobe-dress': V(7, '服: a wardrobe opens, a red shirt and blue trousers fly out onto a person, who twirls in them'),
  'easel-paint': V(6, '画: on an easel a brush paints a hill and a sun; a gold frame drops round the picture'),
  'projector': V((o) => ({ popcorn: 8 })[o.outcome] ?? 6, '映: a projector beam lights a screen behind the kanji, where a little figure runs across; outcome popcorn: an audience in red seats watches a flickering screen, popcorn pops (映画)', { outcome: 'beam' }, 'outcome'),
  'pot-cook': V((o) => ({ pan: 7 })[o.outcome] ?? 7, '料: a carrot, a fish and a rice ball drop into a pot on the stove; a ladle stirs and steam rises; outcome pan: a chef in a tall hat tosses an omelette in a frying pan (料理)', { outcome: 'pot' }, 'outcome'),
  'bus-ride': V((o) => ({ bike: 5 })[o.outcome] ?? 5, '乗: a bus pulls up, a person gets on and waves from the window as it drives off; outcome bike: a kid gets on a bicycle and pedals away (乗る)', { outcome: 'bus' }, 'outcome'),
  'fever': V((o) => ({ touch: 6 })[o.outcome] ?? 6, '熱: a thermometer in a mouth shoots up red, the face goes red, steam puffs from the ears; an ice pack cools them down; outcome touch: a hand touches a steaming kettle and jerks back with a red flash (熱い)', { outcome: 'fever' }, 'outcome'),
  'brush-enso': V((o) => ({ pencil: 4, pen: 4 })[o.outcome] ?? 5, '筆: a big writing brush dips into an ink stone and paints a circle in one sweep, flicking ink; outcome pencil: a pencil writes, then is sharpened, shavings curl (鉛筆); pen: a fountain pen dips in ink and signs (万年筆)', { outcome: 'brush' }, 'outcome'),
  'cow-moo': V((o) => ({ milk: 7, steak: 8 })[o.outcome] ?? 7, '牛: a cow walks in, says モー in rings of sound, and a milk pail fills up; outcome milk: a carton pours milk into a glass, a kid drinks and gets a moustache (牛乳); steak: a steak sizzles and flips on a grill, a little cow sign in it (牛肉)', { outcome: 'cow' }, 'outcome'),
  'heart-beat': V(4, '心: a heart glows in a chest, beating lub-dub; the person hugs themselves and it beats bigger'),
  'parent-watch': V(5, '親: a parent walks with a small kid; the kid runs ahead and the parent climbs a stump to watch over them'),
  'police-box': V(9, '交番: a little police box with a red lamp; the officer bends down and points a lost kid the way'),
  'parasol-up': V(7, '差す: a person sweating under a blazing sun holds a parasol up over their head; it pops open and shade falls'),
  'stopwatch-exact': V(7, '丁度: a stopwatch counts up and a thumb stops it on exactly 10.00; a tick and a sparkle'),
  'plane-takeoff': V(3, '飛行機: a plane speeds down a runway, lifts off and climbs away trailing a contrail'),
  'headphones-dance': V(4, '音楽: a kid with big headphones bobs and dances while colourful notes float out'),
  'cuckoo-clock': V(7, '時計: a cuckoo clock: the hands sweep round to twelve, the door opens and the bird pops out twice'),
  'year-hop': V(7, '再来年: three calendar blocks (now, +1, +2); a kid hops two ahead and cheers'),
  'flower-gasp': V((o) => ({ yum: 6 })[o.outcome] ?? 6, '美: a bud opens into a big pink flower, sparkles circle it; a person gasps, hands on their cheeks; outcome yum: a person bites a rice ball, cheeks glow, hearts and sparkles (美味しい)', { outcome: 'flower' }, 'outcome'),
  'podium-win': V(8, '最: three runners race up to a podium; the winner stands on the top step and lifts a gold trophy'),
  'face-change': V((o) => ({ laugh: 6 })[o.outcome] ?? 6, '面: a big round face smiles, goes wide-eyed with an O mouth, then winks; outcome laugh: a person reading laughs so hard they fall over and roll (面白い)', { outcome: 'face' }, 'outcome'),
  'apple-sell': V((o) => ({ sold: 4 })[o.outcome] ?? 10, '売: a seller behind a crate of apples holds one up; a buyer pays a coin and gets the apple; outcome sold: a big red SOLD stamp slams onto a TV for sale, the seller cheers (売る)', { outcome: 'apple' }, 'outcome'),
  'race-start': V(7, '始: two runners crouch at the start line; the flag drops and they dash off in a puff of dust'),
  'curtain-close': V((o) => ({ open: 7 })[o.outcome] ?? 7, '終: on a little stage an actor bows; the red curtains slide shut and おわり appears on them; outcome open: the curtains part, the spotlight comes up and the actor waves hello (始まる)', { outcome: 'close' }, 'outcome'),
  'move-in': V((o) => ({ crab: 3 })[o.outcome] ?? 6, '住: a person carries a box into a little house; its window lights up and the chimney puffs smoke; outcome crab: a hermit crab climbs into an empty shell and peeks out of its new home (住む)', { outcome: 'house' }, 'outcome'),
  'banana-trip': V(4, '転: a person steps on a banana peel, flips head over heels and lands sitting, stars circling their head'),
  'sick-bed': V((o) => ({ germs: 4 })[o.outcome] ?? 9, '病: a pale person in bed with a red nose and an ice bag sneezes; pills on the nightstand; outcome germs: green spiky germs bounce round a pale sneezing person (病気)', { outcome: 'bed' }, 'outcome'),
  'ambulance': V((o) => ({ doctor: 8 })[o.outcome] ?? 5, '院: an ambulance with a flashing light pulls up at a building with a red cross; its doors slide open; outcome doctor: under a red cross a doctor listens to a kid’s heartbeat and puts on a plaster (病院)', { outcome: 'van' }, 'outcome'),
  'walk-far': V((o) => ({ scope: 5 })[o.outcome] ?? 3, '遠: a person waves goodbye and walks away down a long road towards far mountains, smaller and smaller; outcome scope: through a telescope a zoom circle shows a tiny far-off castle (遠い)', { outcome: 'road' }, 'outcome'),
  'mirror-dance': V((o) => ({ match: 6 })[o.outcome] ?? 5, '同: two people side by side do exactly the same jumping jacks; an equals sign glows above; outcome match: two face-down cards flip over to the same star; an equals sign (同じ)', { outcome: 'dance' }, 'outcome'),
  'wedding': V(10, '夫: a groom in a suit and a bride in white; rings float to them, confetti falls and a heart rises'),
  'post-kick': V((o) => ({ ok: 7, weight: 4 })[o.outcome] ?? 5, '丈: a kid kicks a thick wooden post that does not budge, then hops holding a sore foot; outcome ok: a kid falls, a grown-up rushes over, the kid hops up arms high with a tick (大丈夫); weight: a heavy weight drops on a sturdy table that holds (丈夫)', { outcome: 'post' }, 'outcome'),
  'alarm-wake': V((o) => ({ sun: 7 })[o.outcome] ?? 9, '起: an alarm clock rings and hops; the person asleep in bed sits bolt upright, hair sticking up, and stretches; outcome sun: the morning sun rises in the window, the person sits up and stretches while birds sing (起きる)', { outcome: 'alarm' }, 'outcome'),
  'home-greet': V((o) => ({ bird: 7 })[o.outcome] ?? 8, '帰: a person walks up to a house at dusk; the door opens, warm light spills out and the family comes out for a hug; outcome bird: a mother bird flies home to her nest with a worm, the chicks bounce (帰る)', { outcome: 'house' }, 'outcome'),
  'toast-run': V((o) => ({ tortoise: 3 })[o.outcome] ?? 7, '遅: a kid runs with toast in their mouth, sweat flying, under a clock whose hands spin; outcome tortoise: a tortoise plods along while a rabbit zooms past (遅い)', { outcome: 'toast' }, 'outcome'),
  'mud-splash': V((o) => ({ dishes: 5 })[o.outcome] ?? 4, '汚: a person in white steps in a puddle; mud splashes up and their clothes go brown; outcome dishes: a pile of dirty dishes with stink lines and flies, a person holds their nose (汚い)', { outcome: 'puddle' }, 'outcome'),
  'hand-question': V((o) => ({ mic: 8, quiz: 8, answer: 10, phone: 6 })[o.outcome] ?? 7, '問: a kid raises a hand under a big "?" speech bubble; the grown-up beside scratches their head; outcome mic: a reporter holds out a microphone under a "?" (質問); quiz: a quiz board "?" and a contestant slams the buzzer (問題); answer: the teacher asks "?", a kid answers with a big tick and gets a star (答); phone: a phone rings, a person picks it up and answers (答える)', { outcome: 'hand' }, 'outcome'),
  'title-stamp': V((o) => ({ dog: 5 })[o.outcome] ?? 4, '題: a red title band slams onto a notebook, is underlined, and text lines fill in below; outcome dog: a dog runs off with the homework sheet, the kid gasps (宿題)', { outcome: 'title' }, 'outcome'),
  'inn-sleep': V(10, '宿: a traveller with a suitcase walks into a little inn; the window lights, goes dark and Zzz floats up'),
  'grab-apple': V((o) => ({ claw: 9 })[o.outcome] ?? 4, '取: a hand reaches in, grabs the apple off a table and pulls it away, leaving the table empty; outcome claw: a claw machine grabs a toy and drops it in the chute (取る)', { outcome: 'apple' }, 'outcome'),
  'gem-test': V(8, '真: a magnifying glass passes over two gems: the real one sparkles (tick), the fake cracks (cross)'),
  'photo-snap': V((o) => ({ wall: 5 })[o.outcome] ?? 8, '写: a person poses with a peace sign; the camera flashes and a photo slides out and develops; outcome wall: flash by flash, three photos pin themselves to a cork board (写真)', { outcome: 'camera' }, 'outcome'),
  'ocean-ship': V(4, '洋: waves roll across a wide sea; a ship sails along the horizon, puffing smoke'),
  'hourglass-end': V(7, '終わる: the sand in an hourglass runs out, a bell dings and it glows: time is up'),
  'bike-bell': V(7, '自転車: a kid rides a bicycle across ringing the bell (チリン)'),
  'mannequin': V(7, '洋服: a mannequin on a stand changes outfit with a sparkle: a red dress, a suit and tie, a hat and coat'),
  'travel-road': V((o) => ({ suitcase: 2 })[o.outcome] ?? 9, '旅: a traveller with a backpack and a suitcase walks while the scenery slides past: mountains, the sea, a town; outcome suitcase: a suitcase rolls along and travel stickers pop onto it (旅行)', { outcome: 'walk' }, 'outcome'),
  'pool-swim': V((o) => ({ fish: 4 })[o.outcome] ?? 5, '泳: a swimmer in a cap does the front crawl across a pool, splashes flying; outcome fish: under the waves a fish swims along, bubbles rising (泳ぐ)', { outcome: 'pool' }, 'outcome'),
  'bird-sing': V((o) => ({ pets: 5 })[o.outcome] ?? 6, '鳴: a bird on a branch opens its beak and sings, notes rising; a second bird answers; outcome pets: a cat says ニャー and a dog answers ワン (鳴く)', { outcome: 'birds' }, 'outcome'),
  'stove-warm': V((o) => ({ spring: 4 })[o.outcome] ?? 6, '暖: a frosty shivering person holds their hands to a glowing stove; the frost melts and they relax; outcome spring: the spring sun comes out, snow melts and flowers pop up (暖かい)', { outcome: 'stove' }, 'outcome'),
  'onsen-soak': V((o) => ({ tepid: 5 })[o.outcome] ?? 8, '温: in a rocky outdoor hot spring a person with a towel on their head sinks in; steam, snow, a happy sigh; outcome tepid: a finger tests the bath, a weak wisp of steam, a so-so face (温い)', { outcome: 'onsen' }, 'outcome'),
  'two-buckets': V((o) => ({ parents: 6 })[o.outcome] ?? 4, '両: a person lifts two buckets at once, one in each hand, evenly balanced; outcome parents: a mum and a dad swing their kid up between them (両親)', { outcome: 'buckets' }, 'outcome'),
  'wheelbarrow': V(5, '運: a person pushes a wheelbarrow of boxes; a four-leaf clover drifts down into it with a sparkle'),
  'stand-vase': V((o) => ({ kitchen: 6 })[o.outcome] ?? 4, '台: a hand sets a little wooden stand down, then places a vase of flowers on top; outcome kitchen: a pot boils with a rattling lid, the tap drips, a knife chops (台所)', { outcome: 'vase' }, 'outcome'),
  'coin-keep': V((o) => ({ star: 5 })[o.outcome] ?? 4, '有: a hand opens on a gold coin, closes over it, opens again: still there, it is mine; outcome star: a person waves on a red carpet while camera flashes pop (有名)', { outcome: 'coin' }, 'outcome'),
  'butler-door': V((o) => ({ hardhat: 6 })[o.outcome] ?? 7, '仕: a butler in a bow tie bows and holds the door open while a guest walks in; outcome hardhat: a worker in a hard hat carries a plank and hammers it down (仕事)', { outcome: 'butler' }, 'outcome'),
  'devil-vase': V((o) => ({ thumbsdown: 6 })[o.outcome] ?? 7, '悪: a little red devil sneaks up, knocks a vase off its stand and snickers as it smashes; outcome thumbsdown: a big thumbs down, a frowning face and a drizzling cloud (悪い)', { outcome: 'devil' }, 'outcome'),
  'trunk-thick': V((o) => ({ crayon: 4 })[o.outcome] ?? 3, '太: a thin sapling trunk swells thicker and thicker into a fat old tree; its rings show on a cut slice; outcome crayon: a thin pencil line and a fat crayon line side by side (太い)', { outcome: 'tree' }, 'outcome'),
  'words-fly': V((o) => ({ slam: 3 })[o.outcome] ?? 5, '辞: letter tiles fly out of an open book in arcs and line up into a word above it, glowing; outcome slam: a thick dictionary opens, pages flutter, then it slams shut in a puff of dust (辞書)', { outcome: 'tiles' }, 'outcome'),
  'boomerang-throw': V((o) => ({ book: 5 })[o.outcome] ?? 4, '返: a person throws a boomerang; it swings out in a wide loop and comes back to their hand; outcome book: a kid slides a borrowed book back into a library return box; a ding (返す)', { outcome: 'boomerang' }, 'outcome'),
  'memory-bubble': V((o) => ({ cards: 7 })[o.outcome] ?? 7, '覚: a person reads; pictures float up out of the book into a thought bubble above their head and stay; outcome cards: flashcards flip, the last flies into the head and a bulb lights (覚える)', { outcome: 'bubble' }, 'outcome'),
  'office-work': V((o) => ({ class: 13 })[o.outcome] ?? 7, '業: a grown-up types at a laptop; finished papers stack higher and higher while the clock spins; outcome class: a classroom from behind the desks, the teacher writes on the board, the bell rings (授業)', { outcome: 'office' }, 'outcome'),
  // ---- Step 1 (Step 2c): step1-*.js ----
  'three-ducks': V((o) => ({ count: 3, day: 5 })[o.outcome] ?? 4, '三: three ducks waddle up beside the kanji; each quacks in turn under a badge counting 1, 2, 3 while the matching stroke hops; they turn and waddle off; outcome count: three dango drop onto a stick, counted (三つ); day: a month grid lights day by day to the 3rd, ringed, and a duck hops onto it (三日)', { outcome: 'ducks' }, 'outcome'),
  'moon-wax': V((o) => (o.outcome === 'week' ? 6 : 3), '月: in the night beside the kanji the moon grows from a thin crescent to full, glows, and wanes again while stars twinkle; outcome week: smaller, with the weekday strip lighting 月 (月曜日)', { outcome: 'moon' }, 'outcome'),
  'river-flow': V(3, '川: grass on the banks; the three strokes ripple like running water and a paper boat drifts down the middle one and floats away downstream'),
  'balloon-up': V((o) => (o.outcome === 'flag' ? 3 : 4), '上: a gift box pops and a red balloon rises out of it, up past the kanji to float above it, then sails off upwards; outcome flag: a flag is hauled up a pole to the top, confetti (上げる)', { outcome: 'balloon' }, 'outcome'),
  'dog-fetch': V(6, '犬: a dog sits wagging beside the kanji; a ball bounces past, the dog dashes after it, brings it back in its mouth, drops it and jumps for joy'),
  'car-beep': V(6, '車: a car comes up a road from the distance, parks beside the kanji, beeps twice with its lights flashing and backs away'),
  'mouth-open': V(5, '口: the glyph is a mouth: the bottom stroke drops like a jaw showing teeth and a tongue that pokes out and waggles; it shuts, opens wide for a big あー, and shuts'),
  'sun-rise': V((o) => (o.outcome === 'week' ? 8 : 5), '日: night with stars; the sun climbs out from behind a hill, pushes the dark away and spins out its rays, then sinks again; outcome week: with the weekday strip lighting 日 (日曜日)', { outcome: 'sun' }, 'outcome'),
  'fire-catch': V((o) => (o.outcome === 'week' ? 10 : 7), '火: a match strikes on a box and drops onto a pile of logs; flames catch, grow and roar, sparks fly; it dies down to embers; outcome week: 火曜日', { outcome: 'fire' }, 'outcome'),
  'tap-fill': V((o) => (o.outcome === 'week' ? 10 : 7), '水: a tap above a glass basin turns on; water pours down, the basin fills with rings spreading and drops jumping; the tap shuts and it drains; outcome week: 水曜日', { outcome: 'tap' }, 'outcome'),
  'mountain-rise': V(4, '山: a rumble shakes the kanji; a big mountain rises out of the ground behind it in a cloud of dust, snow falls and caps its peak; then it sinks back'),
  'tree-sprout': V((o) => (o.outcome === 'week' ? 7 : 4), '木: the kanji is the trunk: twigs sprout, a crown of leaves bursts out on top, an apple grows, falls and bounces, leaves drift down; outcome week: 木曜日', { outcome: 'tree' }, 'outcome'),
  'rain-drops': V(3, '雨: a grey cloud gathers over the kanji; its four dots fall out of it as rain with more drops behind them, splash in rings on the ground and draw back in'),
  'sun-moon-glow': V(5, '明: night; the 日 half lights up gold like the sun and the 月 half silver like the moon, beams sweep out and the dark lifts; then night falls again'),
  'grove-grow': V(3, '林: both 木 grow crowns, then little trees pop up one after another beside them into a small wood and a squirrel scampers along in front'),
  'one-candle': V((o) => ({ count: 2, first: 7 })[o.outcome] ?? 5, '一: one cupcake drops onto the stroke; its one candle lights under a "1" badge and is blown out; outcome count: one apple (一つ); first: the old month\'s page peels off and flies away, day 1 of the new month lights with a ring (一日 ついたち); allday: one sun rises on the left, arcs over the word and sets on the right (一日 いちにち)', { outcome: 'candle' }, 'outcome'),
  'two-birds': V((o) => ({ count: 2, day: 5 })[o.outcome] ?? 5, '二: two birds fly in and land on the two strokes as if on wires, each dips, chirps under a badge 1, 2, and they fly off; outcome count: two eggs (二つ); day: the 2nd, a bird (二日)', { outcome: 'birds' }, 'outcome'),
  'four-clover': V((o) => ({ count: 2, day: 5 })[o.outcome] ?? 4, '四: a stem grows; four heart leaves unfold one at a time, counted 1-4, and the lucky clover sparkles; outcome count: four clovers (四つ); day: the 4th (四日)', { outcome: 'clover' }, 'outcome'),
  'ten-strike': V((o) => (o.outcome === 'day' || o.outcome === 'day20' ? 5 : 6), '十: a bowling ball rolls up a lane into ten pins in a triangle and knocks them all flying: STRIKE, 10; outcome day: the 10th, a pin (十日); day20: the 20th (二十日)', { outcome: 'pins' }, 'outcome'),
  'rainbow-seven': V((o) => ({ count: 2, day: 5 })[o.outcome] ?? 3, '七: a rainbow builds itself stripe by stripe, seven colours counted 1-7, clouds at its feet; outcome count: seven rainbow balls (七つ); day: the 7th, a little rainbow (七日)', { outcome: 'rainbow' }, 'outcome'),
  'this-unit': V((o) => rowDc(o.unit ?? 'now') + 2, '今: a row of three tiles of the unit (now: clocks; day: suns; week: seven dots; month: 9月 10月 11月; year: 2025 2026 2027); a spotlight comes down on the middle one, a frame lands round it and it bounces: this one, now (今日 今週 今月 今年)', { unit: 'now' }, 'unit'),
  'next-unit': V((o) => rowDc(o.unit ?? 'year') + 2, '来: the tiles of the unit; the frame sits on the middle one, an arrow points right, the frame steps onto the next tile, which pops (来週 来月 来年)', { unit: 'year' }, 'unit'),
  'last-unit': V((o) => rowDc(o.unit ?? 'month') + 2, '先: the tiles of the unit, the left one faded like an old photo; an arrow points back and the frame steps onto it (先週 先月)', { unit: 'month' }, 'unit'),
  'every-unit': V((o) => ((o.unit ?? 'cups') === 'cups' ? 4 : rowDc(o.unit) + 2), '毎: unit cups: a teapot hops along a row of cups and fills every one; day / week / month / year: a stamp hops along the tiles and stamps a red tick on every one (毎日 毎週 毎月 毎年)', { unit: 'cups' }, 'unit'),
  'year-seasons': V(5, '年: a little tree runs through the seasons (pink blossom, green, red leaves, bare with snow) and a counter ticks the year on when winter ends'),
  'clock-hours': V((o) => (o.outcome === 'sometimes' || o.outcome === 'span' ? 5 : 4), '時: a clock beside the kanji: the long hand sweeps round, the short hand steps an hour each turn and a bell on top rings on the hour; outcome sometimes: a bird pops out of the top only now and then (時々); span: a coloured wedge fills the face as the hands move on (時間)', { outcome: 'hours' }, 'outcome'),
  'rest-tree': V((o) => ({ holiday: 6, bed: 9 })[o.outcome] ?? 6, '休: a tired walker wipes their brow, sits down against a tree, nods off, Zzz, then gets up and walks on; outcome holiday: a person swings in a hammock under the sun (休み); bed: an alarm rings by a bed, a hand pushes it away and the sleeper snuggles back down, Zzz (休む)', { outcome: 'tree' }, 'outcome'),
  'anchor-drop': V((o) => (o.outcome === 'please' ? 4 : 7), '下: a boat on the water; its anchor drops down on a chain to the sea bed below, sand puffs, bubbles rise; it is wound back up; outcome please: a kid holds out both hands, a sweet drops into them and they bow (下さい)', { outcome: 'anchor' }, 'outcome'),
  'what-box': V(6, '何: a box with a "?" on it shakes and hops; the lid pops and a big "?" springs out on a spring, wobbling'),
  'kanji-walker': V((o) => (o.outcome === 'alone' ? 8 : 3), '人: the glyph walks on its two strokes as legs: a head pops on top, it steps along, waves and walks back; outcome alone: one person sits alone on a bench under a lamp, swinging their feet, a leaf blowing past (一人)', { outcome: 'walk' }, 'outcome'),
  'high-five': V(5, '手: two big hands swing in and meet in a high five with a burst, wave and swing out'),
  'chat-table': V((o) => (o.outcome === 'phone' ? 5 : 7), '話: two people sit at a little table and talk, speech bubbles popping up from one then the other; outcome phone: one person talks and talks with big gestures, bubbles of squiggles floating up (話す)', { outcome: 'table' }, 'outcome'),
  'peek-behind': V((o) => (o.outcome === 'sneak' ? 4 : 3), '後: a kid hides behind the kanji, peeks out round its side, ducks back, then pops up over the top giggling; outcome sneak: a cat creeps up behind a person, who spins round, "!" (後ろ)', { outcome: 'peek' }, 'outcome'),
  'grow-big': V((o) => (o.outcome === 'elephant' || o.outcome === 'whale' ? 4 : 3), '大: the kanji swells up huge while a tiny mouse at its foot looks up and up, "!"; outcome elephant: a huge elephant beside a tiny mouse raises its trunk and trumpets (大きい); whale: a huge whale surfaces beside a little boat and spouts (大きな)', { outcome: 'glyph' }, 'outcome'),
  'adult-kid': V(7, '大人: a tall grown-up in a suit with a briefcase beside a small kid, who stretches up on tiptoe and only reaches their waist; the grown-up pats their head'),
  'house-out': V(7, '外: a little house; the door swings open, a dog bounds out into the yard and the door shuts; the dog sniffs a flower, then trots back in'),
  'octopus-eight': V((o) => ({ count: 3, day: 5 })[o.outcome] ?? 3, '八: an octopus pops up beside the kanji and lifts its arms one at a time, counted 1-8, then waves all eight; outcome count: eight takoyaki drop onto a tray (八つ); day: the 8th, a little octopus (八日)', { outcome: 'octopus' }, 'outcome'),
  'dice-six': V((o) => ({ count: 3, day: 5 })[o.outcome] ?? 4, '六: a big die tumbles in, bounces and lands showing six; its pips light up one by one, counted; outcome count: six eggs drop into an egg box (六つ); day: the 6th, a die (六日)', { outcome: 'die' }, 'outcome'),
  'ttt-nine': V((o) => ({ count: 3, day: 5 })[o.outcome] ?? 4, '九: a noughts-and-crosses grid fills with nine marks, X and O in turn, counted 1-9; outcome count: nine marbles in a tray (九つ); day: the 9th, a cross (九日)', { outcome: 'grid' }, 'outcome'),
  'come-here': V((o) => (o.outcome === 'bird' ? 4 : 6), '来: a hand beckons; far off a puppy bounds closer and closer and jumps up to it, wagging; outcome bird: a bird flies in from far away and lands on a held-out finger (来る)', { outcome: 'puppy' }, 'outcome'),
  'boat-race': V(4, '先: three paper boats race on the water; the red one pulls ahead and its little flag pops up: first, ahead'),
  'weekday-wheel': V(3, '曜: a wheel of the seven day symbols (moon, fire, water, tree, gold, soil, sun) spins and slows until the pointer stops on one, which glows'),
  'week-hop': V(3, '週: a strip of seven days; a little sun hops from day to day, each lighting as it lands, and after Sunday hops back round to Monday'),
  'snow-white': V((o) => (o.outcome === 'rabbit' ? 4 : 6), '白: snow falls and settles on the kanji, a little tree and the ground until everything is white; then it melts; outcome rabbit: a white rabbit hops through the snow leaving prints (白い)', { outcome: 'snow' }, 'outcome'),
  'turtle-out': V((o) => ({ door: 4, exit: 5, hat: 6 })[o.outcome] ?? 3, '出: a still turtle shell; out pops its head, then its legs, it walks a few steps and pulls back in; outcome door: a door opens and a person walks out, waving (出る); hat: a wand taps a top hat and a rabbit rises out of it (出す); exit: a green 出口 sign glows over a door and a person runs out under it (出口)', { outcome: 'turtle' }, 'outcome'),
  'tent-in': V((o) => ({ coin: 3 })[o.outcome] ?? 5, '入: a dog trots into a little tent, the flap drops behind it and the tent wiggles; then it pokes its head out; outcome house: a person walks into a house, the door shuts, the window lights (入る); doors: glass doors under an 入口 sign slide open and a person walks in (入り口); coin: a coin drops into a piggy bank, which jiggles (入れる)', { outcome: 'tent' }, 'outcome'),
  'lightning-bulb': V(5, '電: lightning zaps between two dark clouds and down into a light bulb, which lights up; outcome phone: an old phone rings and hops, sparks running along its cord (電話); bulb: sparks run along a power line into a little house whose windows light up (電気)', { outcome: 'bolt' }, 'outcome'),
  'electric-train': V(5, '電車: a train runs along under an overhead wire, its pantograph sparking'),
  'feet-walk': V(2, '足: two bare feet walk across beside the kanji leaving footprints, stop and wiggle their toes'),
  'hen-lead': V(4, '前: a hen walks in front with three chicks behind her in a line; a glowing ring and an arrow mark the one in front'),
  'road-unroll': V(5, '道: a winding road unrolls from your feet over green hills to a far-off house, trees popping up along it'),
  'sprout-life': V(5, '生: a seed in a mound of soil cracks, a sprout pushes up, unfolds two leaves, stretches up and smiles, alive; outcome stork: a stork flies in with a bundle and sets it in a basket, hearts (生まれる)', { outcome: 'sprout' }, 'outcome'),
  'station-train': V(5, '駅: a station platform with a name board えき and a clock; a train pulls in, stops, its doors light up, and pulls out'),
  'flower-bloom': V(5, '花: a bud on a stem swells and opens its petals one by one into a big flower; a bee buzzes round it and lands'),
  'dad-shoulders': V((o) => (o.outcome === 'home' ? 7 : 5), '父: a dad with a moustache lifts his kid onto his shoulders; the kid cheers, arms up, as he sways; outcome home: dad comes home with his briefcase and the kid runs to him and is swung up high (お父さん)', { outcome: 'shoulders' }, 'outcome'),
  'mum-cradle': V(6, '母: a mum rocks a baby in her arms, hearts and a lullaby note rising; outcome cook: mum in an apron stirs a steaming pot, lifts the ladle and tastes (お母さん)', { outcome: 'cradle' }, 'outcome'),
  'me-me': V(4, '私: a kid jumps up and down waving a hand high, then points at their own chest: "わたし!" (me)'),
  'plough-man': V((o) => (o.outcome === 'boy' ? 4 : 6), '男: a man leans into a plough and drags it through the rice field, a furrow opening behind him; outcome boy: a boy runs round holding a toy plane up high (男の子)', { outcome: 'plough' }, 'outcome'),
  'woman-twirl': V(5, '女: a woman with long hair and a flower in it twirls in her dress, the skirt flaring, petals drifting; outcome girl: a girl with pigtails swings high on a swing (女の子)', { outcome: 'twirl' }, 'outcome'),
  binoculars: V((o) => ({ stars: 4, show: 4 })[o.outcome] ?? 6, '見: a person lifts binoculars and looks left and right; a bird lands far off, they stop on it, "!", and wave; outcome stars: a telescope turns up to the stars and a shooting star streaks past (見る); show: a kid holds up a drawing to show you, bouncing proudly (見せる)', { outcome: 'bird' }, 'outcome'),
  'abacus-kid': V((o) => ({ caps: 2 })[o.outcome] ?? 6, '学: a kid at a table flicks the beads of an abacus, counting, then lifts a hand and a bulb lights: got it; outcome backpack: a student in a cap with a school bag and books walks to school (学生); caps: graduation caps fly up and spin down with confetti (大学)', { outcome: 'abacus' }, 'outcome'),
  'teacher-bow': V(8, '先生: a teacher with glasses and a pointer bows; two pupils bow back'),
  kit: V(21, 'review sheet of the props kit: hand poses, a person walking, hammer, nail, board, plate, ball, heart, burst (not for cards)', { pose: 'all' }),
};
